import asyncio

from alembic import command
from db.testing import alembic_config, migrated_postgres
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine


async def _insert_legacy_motif(url: str) -> None:
    engine = create_async_engine(url)
    try:
        async with engine.begin() as connection:
            await connection.execute(
                text(
                    "INSERT INTO motifs (id, symbol, bbox, anchor) "
                    "VALUES ('recraft-legacylabels', '<symbol/>', "
                    "'[-0.5,-0.5,0.5,0.5]'::jsonb, '[0,0]'::jsonb)"
                )
            )
    finally:
        await engine.dispose()


async def _legacy_metadata(url: str) -> tuple[object, object, object]:
    engine = create_async_engine(url)
    try:
        async with engine.connect() as connection:
            row = (
                await connection.execute(
                    text(
                        "SELECT slot_labels, ingested_user_id, ingested_session_id "
                        "FROM motifs WHERE id = 'recraft-legacylabels'"
                    )
                )
            ).one()
            return row[0], row[1], row[2]
    finally:
        await engine.dispose()


def test_upgrade_head_applies_and_matches_models():
    with migrated_postgres() as url:
        config = alembic_config(url)
        command.downgrade(config, "8ce7aff0df59")
        asyncio.run(_insert_legacy_motif(url))
        command.upgrade(config, "head")
        assert asyncio.run(_legacy_metadata(url)) == (None, None, None)

        # The new revision itself must be reversible, then remain drift-free on re-upgrade.
        command.downgrade(config, "8ce7aff0df59")
        command.upgrade(config, "head")
        # 모델 ↔ 리비전 드리프트가 있으면 AutogenerateDiffsDetected로 실패
        command.check(config)
