from alembic import command
from db.testing import alembic_config, migrated_postgres


def test_upgrade_head_applies_and_matches_models():
    with migrated_postgres() as url:
        # 모델 ↔ 리비전 드리프트가 있으면 AutogenerateDiffsDetected로 실패
        command.check(alembic_config(url))
