import asyncio
import uuid

from alembic import command
from db.testing import POSTGRES_IMAGE, alembic_config, migrated_postgres
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine
from testcontainers.postgres import PostgresContainer


def test_upgrade_head_applies_and_matches_models():
    with migrated_postgres() as url:
        # 모델 ↔ 리비전 드리프트가 있으면 AutogenerateDiffsDetected로 실패
        command.check(alembic_config(url))


def test_backfill_order_item_product_snapshot():
    """c7d2e94a5b18: 스냅샷 없는 레거시 product 주문 항목을 현재 상품 값으로 백필한다."""
    user_id, order_id, option_id = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    plain_item, optioned_item, reform_item = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()

    async def run(url: str, sql: str, params: dict | list[dict] | None = None):
        engine = create_async_engine(url)
        try:
            async with engine.begin() as conn:
                result = await conn.execute(text(sql), params)
                return (
                    result.mappings().all() if sql.lstrip().upper().startswith("SELECT") else None
                )
        finally:
            await engine.dispose()

    with PostgresContainer(POSTGRES_IMAGE, driver="asyncpg") as pg:
        url = pg.get_connection_url()
        cfg = alembic_config(url)
        command.upgrade(cfg, "eaac110cb362")  # 백필 직전 리비전

        asyncio.run(
            run(url, "INSERT INTO users (id, name) VALUES (:id, '테스터')", {"id": user_id})
        )
        asyncio.run(
            run(
                url,
                "INSERT INTO products "
                "(id, name, price, image, category, color, pattern, material, info) "
                "VALUES (1, '실크 넥타이', 41000, 'tie.png', '3fold', 'navy', "
                "'solid', 'silk', '설명')",
            )
        )
        asyncio.run(
            run(
                url,
                "INSERT INTO product_options (id, product_id, name, additional_price) "
                "VALUES (:id, 1, '와이드 8cm', 2000)",
                {"id": option_id},
            )
        )
        asyncio.run(
            run(
                url,
                "INSERT INTO orders (id, user_id, order_number, total_price, original_price) "
                "VALUES (:id, :user_id, 'ORD-20260101-001', 41000, 41000)",
                {"id": order_id, "user_id": user_id},
            )
        )
        asyncio.run(
            run(
                url,
                "INSERT INTO order_items "
                "(id, order_id, item_id, item_type, product_id, selected_option_id, "
                "item_data, quantity, unit_price) "
                "VALUES (:id, :order_id, :item_id, :item_type, :product_id, "
                ":selected_option_id, CAST(:item_data AS jsonb), 1, 41000)",
                [
                    {
                        "id": plain_item,
                        "order_id": order_id,
                        "item_id": "product:1",
                        "item_type": "product",
                        "product_id": 1,
                        "selected_option_id": None,
                        "item_data": None,
                    },
                    {
                        "id": optioned_item,
                        "order_id": order_id,
                        "item_id": f"product:1:{option_id}",
                        "item_type": "product",
                        "product_id": 1,
                        "selected_option_id": str(option_id),
                        "item_data": None,
                    },
                    {
                        "id": reform_item,
                        "order_id": order_id,
                        "item_id": "reform:abc",
                        "item_type": "reform",
                        "product_id": None,
                        "selected_option_id": None,
                        "item_data": '{"width": 8}',
                    },
                ],
            )
        )

        command.upgrade(cfg, "head")

        rows = asyncio.run(run(url, "SELECT id, item_data FROM order_items"))
        assert rows is not None
        by_id = {row["id"]: row["item_data"] for row in rows}

        plain = by_id[plain_item]
        assert plain["product"] == {
            "id": 1,
            "code": None,
            "name": "실크 넥타이",
            "image": "tie.png",
            "category": "3fold",
        }
        assert plain["option"] is None

        optioned = by_id[optioned_item]
        assert optioned["product"]["name"] == "실크 넥타이"
        assert optioned["option"] == {
            "id": str(option_id),
            "name": "와이드 8cm",
            "additional_price": 2000,
        }

        # product 외 타입의 기존 스냅샷은 건드리지 않는다
        assert by_id[reform_item] == {"width": 8}
