"""add motifs slot_colors

Revision ID: 8ce7aff0df59
Revises: dadd999bf858
Create Date: 2026-07-24 14:28:16.641950

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8ce7aff0df59'
down_revision: str | None = 'dadd999bf858'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motifs', sa.Column('slot_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motifs', 'slot_colors')
    # ### end Alembic commands ###
