"""baseline

Revision ID: dadd999bf858
Revises:
Create Date: 2026-07-22 23:52:40.983417

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dadd999bf858"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupons",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("discount_type", sa.Text(), nullable=False),
        sa.Column("discount_value", sa.Numeric(), nullable=False),
        sa.Column("max_discount_amount", sa.Numeric(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_type IN ('percentage', 'fixed')", name=op.f("ck_coupons_discount_type")
        ),
        sa.CheckConstraint("discount_value > 0", name=op.f("ck_coupons_discount_value")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
        sa.UniqueConstraint("name", name=op.f("uq_coupons_name")),
    )
    op.create_index(
        "ix_coupons_admin_list", "coupons", ["is_active", "expiry_date", "id"], unique=False
    )
    op.create_table(
        "manual_orders",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("customer_name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("shipping_fee", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_received", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_paid", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "items",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_manual_orders_amount")),
        sa.CheckConstraint("shipping_fee >= 0", name=op.f("ck_manual_orders_shipping_fee")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_orders")),
    )
    op.create_index(
        "ix_manual_orders_admin_list", "manual_orders", ["order_date", "id"], unique=False
    )
    op.create_table(
        "motifs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column(
            "color_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[\"s0\"]'::jsonb"),
            nullable=False,
        ),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("anchor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("view", sa.Text(), nullable=True),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("style", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("embedding_vertex", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("source", sa.Text(), server_default="recraft", nullable=False),
        sa.Column("quality", sa.REAL(), nullable=True),
        sa.Column("variant_group", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope IS NULL OR scope IN ('whole', 'partial')", name=op.f("ck_motifs_scope")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_motifs")),
    )
    op.create_index(
        "ix_motifs_embedding_vertex_halfvec_hnsw",
        "motifs",
        [sa.literal_column("(embedding_vertex::halfvec(3072))").label("embedding_vertex_halfvec")],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding_vertex_halfvec": "halfvec_cosine_ops"},
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("material", sa.Text(), nullable=False),
        sa.Column("info", sa.Text(), nullable=False),
        sa.Column("detail_images", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("option_label", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('3fold', 'sfolderato', 'knit', 'bowtie')",
            name=op.f("ck_products_category"),
        ),
        sa.CheckConstraint(
            "color IN ('black', 'navy', 'gray', 'wine', 'blue', 'brown', 'beige', 'silver')",
            name=op.f("ck_products_color"),
        ),
        sa.CheckConstraint(
            "material IN ('silk', 'cotton', 'polyester', 'wool')", name=op.f("ck_products_material")
        ),
        sa.CheckConstraint(
            "pattern IN ('solid', 'stripe', 'dot', 'check', 'paisley')",
            name=op.f("ck_products_pattern"),
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_price")),
        sa.CheckConstraint("stock IS NULL OR stock >= 0", name=op.f("ck_products_stock")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("code", name=op.f("uq_products_code")),
    )
    op.create_index(
        "ix_products_admin_list", "products", ["category", "created_at", "id"], unique=False
    )
    op.create_table(
        "seamless_generation_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("input_type", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column(
            "has_reference_image", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("reference_image_bytes", sa.Integer(), nullable=True),
        sa.Column("colorway", sa.Text(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("candidate_count_requested", sa.Integer(), nullable=True),
        sa.Column("candidate_count_returned", sa.Integer(), nullable=True),
        sa.Column("distinct_layouts", sa.Integer(), nullable=True),
        sa.Column("available_strategies", sa.Integer(), nullable=True),
        sa.Column("engine_version", sa.Text(), nullable=True),
        sa.Column("registry_version", sa.Text(), nullable=True),
        sa.Column("intent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("generate_ms", sa.Numeric(), nullable=True),
        sa.Column("render_ms", sa.Numeric(), nullable=True),
        sa.Column("status", sa.Text(), server_default="success", nullable=False),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "diagnostics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_type IN ('intent', 'prompt', 'reference_image')",
            name=op.f("ck_seamless_generation_logs_input_type"),
        ),
        sa.CheckConstraint(
            "status IN ('success', 'partial', 'error')",
            name=op.f("ck_seamless_generation_logs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seamless_generation_logs")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("customer", "admin", "manager", name="user_role"),
            server_default="customer",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("birth", sa.Date(), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "notification_consent", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "notification_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "marketing_kakao_sms_consent",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "admin_operation_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("operation_id", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("target_count", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_count IS NULL OR target_count >= 0",
            name=op.f("ck_admin_operation_logs_target_count"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_admin_operation_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_operation_logs")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_admin_operation_logs_operation_id")),
    )
    op.create_index(
        op.f("ix_admin_operation_logs_actor_id"), "admin_operation_logs", ["actor_id"], unique=False
    )
    op.create_index(
        "ix_admin_operation_logs_created_at",
        "admin_operation_logs",
        ["created_at", "id"],
        unique=False,
    )
    op.create_table(
        "admin_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_admin_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_admin_settings")),
    )
    op.create_table(
        "authoring_examples",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("example_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), server_default="bootstrap", nullable=False),
        sa.Column("contract_version", sa.Integer(), nullable=False),
        sa.Column("family", sa.Text(), nullable=False),
        sa.Column("motif_count", sa.Integer(), nullable=False),
        sa.Column("retrieval_text", sa.Text(), nullable=False),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("structural_fingerprint", sa.Text(), nullable=False),
        sa.Column("source_digest", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.Text(), nullable=False),
        sa.Column("embedding_vertex", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("active_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_updated_by", sa.Uuid(), nullable=True),
        sa.Column("active_reason", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "family IN ('solid', 'stripe', 'lattice', 'scatter', 'path', 'point_set', 'stripe_motif', 'multi_motif')",
            name=op.f("ck_authoring_examples_family"),
        ),
        sa.CheckConstraint(
            "source IN ('bootstrap', 'promoted')", name=op.f("ck_authoring_examples_source")
        ),
        sa.CheckConstraint(
            "NOT active OR (embedding_vertex IS NOT NULL AND approved_at IS NOT NULL)",
            name=op.f("ck_authoring_examples_active_ready"),
        ),
        sa.CheckConstraint(
            "contract_version > 0", name=op.f("ck_authoring_examples_contract_version_positive")
        ),
        sa.CheckConstraint(
            "motif_count BETWEEN 0 AND 2", name=op.f("ck_authoring_examples_motif_count")
        ),
        sa.ForeignKeyConstraint(
            ["active_updated_by"],
            ["users.id"],
            name=op.f("fk_authoring_examples_active_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_authoring_examples_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authoring_examples")),
        sa.UniqueConstraint("example_id", name=op.f("uq_authoring_examples_example_id")),
    )
    op.create_index(
        "ix_authoring_examples_active_family",
        "authoring_examples",
        ["active", "family"],
        unique=False,
    )
    op.create_index(
        "uq_authoring_examples_active_fingerprint",
        "authoring_examples",
        ["structural_fingerprint"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "design_sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("colorway", sa.Text(), nullable=True),
        sa.Column("registry_version", sa.Text(), nullable=True),
        sa.Column("current_intent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recraft_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'finalized')", name=op.f("ck_design_sessions_status")
        ),
        sa.CheckConstraint("recraft_used >= 0", name=op.f("ck_design_sessions_recraft_used")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_design_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_sessions")),
    )
    op.create_index(
        op.f("ix_design_sessions_user_id"), "design_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("claim_token_hash", sa.Text(), nullable=True),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("upload_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_images_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
    )
    op.create_index(
        "ix_images_deletion_claimed",
        "images",
        ["deletion_claimed_at"],
        unique=False,
        postgresql_where=sa.text("deletion_claimed_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index("ix_images_entity", "images", ["entity_type", "entity_id"], unique=False)
    op.create_index(
        "ix_images_expires",
        "images",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "uq_images_reform_upload",
        "images",
        ["entity_type", "entity_id"],
        unique=True,
        postgresql_where=sa.text("entity_type = 'reform_upload'"),
    )
    op.create_index(
        "uq_images_repair_shipping_upload",
        "images",
        ["entity_type", "entity_id"],
        unique=True,
        postgresql_where=sa.text("entity_type = 'repair_shipping_upload'"),
    )
    op.create_table(
        "inquiries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.Text(), server_default="일반", nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="답변대기", nullable=False),
        sa.Column("is_secret", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("answer_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_by", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('일반', '상품', '수선', '주문제작', '샘플제작')",
            name=op.f("ck_inquiries_category"),
        ),
        sa.CheckConstraint("status IN ('답변대기', '답변완료')", name=op.f("ck_inquiries_status")),
        sa.CheckConstraint(
            "char_length(content) BETWEEN 1 AND 5000", name=op.f("ck_inquiries_content_length")
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 200", name=op.f("ck_inquiries_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["answered_by"],
            ["users.id"],
            name=op.f("fk_inquiries_answered_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inquiries_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_inquiries_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inquiries")),
    )
    op.create_index(
        "ix_inquiries_admin_list", "inquiries", ["status", "created_at", "id"], unique=False
    )
    op.create_index(op.f("ix_inquiries_product_id"), "inquiries", ["product_id"], unique=False)
    op.create_index(
        "ix_inquiries_public_list", "inquiries", ["category", "created_at", "id"], unique=False
    )
    op.create_index(op.f("ix_inquiries_user_id"), "inquiries", ["user_id"], unique=False)
    op.create_table(
        "notification_preference_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("previous_notification_consent", sa.Boolean(), nullable=False),
        sa.Column("new_notification_consent", sa.Boolean(), nullable=False),
        sa.Column("previous_notification_enabled", sa.Boolean(), nullable=False),
        sa.Column("new_notification_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preference_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preference_logs")),
    )
    op.create_index(
        op.f("ix_notification_preference_logs_user_id"),
        "notification_preference_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "phone_verifications",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "failed_attempts >= 0", name=op.f("ck_phone_verifications_failed_attempts_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_phone_verifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_verifications")),
    )
    op.create_index(
        op.f("ix_phone_verifications_user_id"), "phone_verifications", ["user_id"], unique=False
    )
    op.create_table(
        "pricing_constants",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "category IN ('custom_order', 'fabric', 'reform', 'token', 'sample_discount')",
            name=op.f("ck_pricing_constants_category"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_pricing_constants_amount")),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_pricing_constants_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_pricing_constants")),
    )
    op.create_table(
        "product_likes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_likes_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_product_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_likes")),
        sa.UniqueConstraint(
            "user_id", "product_id", name=op.f("uq_product_likes_user_id_product_id")
        ),
    )
    op.create_index(
        op.f("ix_product_likes_product_id"), "product_likes", ["product_id"], unique=False
    )
    op.create_table(
        "product_options",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("additional_price", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "additional_price >= 0", name=op.f("ck_product_options_additional_price")
        ),
        sa.CheckConstraint("stock IS NULL OR stock >= 0", name=op.f("ck_product_options_stock")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_options_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_options")),
        sa.UniqueConstraint("product_id", "name", name=op.f("uq_product_options_product_id_name")),
    )
    op.create_index(
        op.f("ix_product_options_product_id"), "product_options", ["product_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("session_kind", sa.Text(), server_default="store", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "session_kind IN ('store', 'admin')", name=op.f("ck_refresh_tokens_session_kind")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_index(
        "ix_refresh_tokens_user_id_session_kind",
        "refresh_tokens",
        ["user_id", "session_kind"],
        unique=False,
    )
    op.create_table(
        "shipping_addresses",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_name", sa.Text(), nullable=False),
        sa.Column("recipient_phone", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("address_detail", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("delivery_memo", sa.Text(), nullable=True),
        sa.Column("delivery_request", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_shipping_addresses_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipping_addresses")),
    )
    op.create_index(
        op.f("ix_shipping_addresses_user_id"), "shipping_addresses", ["user_id"], unique=False
    )
    op.create_table(
        "token_purchases",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("payment_group_id", sa.Uuid(), nullable=False),
        sa.Column("plan_key", sa.Text(), nullable=False),
        sa.Column("token_amount", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="대기중", nullable=False),
        sa.Column("payment_key", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plan_key IN ('starter', 'popular', 'pro')", name=op.f("ck_token_purchases_plan_key")
        ),
        sa.CheckConstraint(
            "status IN ('대기중', '결제중', '완료', '실패')", name=op.f("ck_token_purchases_status")
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_token_purchases_price")),
        sa.CheckConstraint("token_amount > 0", name=op.f("ck_token_purchases_token_amount")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_token_purchases_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_purchases")),
        sa.UniqueConstraint("payment_group_id", name=op.f("uq_token_purchases_payment_group_id")),
    )
    op.create_index(
        op.f("ix_token_purchases_user_id"), "token_purchases", ["user_id"], unique=False
    )
    op.create_table(
        "user_coupons",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("coupon_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'used', 'expired', 'revoked', 'reserved')",
            name=op.f("ck_user_coupons_status"),
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"], ["coupons.id"], name=op.f("fk_user_coupons_coupon_id_coupons")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_coupons_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_coupons")),
        sa.UniqueConstraint("user_id", "coupon_id", name=op.f("uq_user_coupons_user_id_coupon_id")),
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_user_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('google', 'kakao', 'apple', 'naver')",
            name=op.f("ck_user_identities_provider"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint(
            "provider",
            "provider_user_id",
            name=op.f("uq_user_identities_provider_provider_user_id"),
        ),
    )
    op.create_index(
        op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False
    )
    op.create_table(
        "user_motifs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("motif_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["motif_id"], ["motifs.id"], name=op.f("fk_user_motifs_motif_id_motifs")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_motifs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_motifs")),
        sa.UniqueConstraint("user_id", "motif_id", name=op.f("uq_user_motifs_user_id_motif_id")),
    )
    op.create_index(op.f("ix_user_motifs_user_id"), "user_motifs", ["user_id"], unique=False)
    op.create_table(
        "authoring_promotion_candidates",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_key", sa.Text(), nullable=False),
        sa.Column("source_generation_log_id", sa.Uuid(), nullable=True),
        sa.Column("plan_index", sa.Integer(), nullable=False),
        sa.Column("selected_candidate_id", sa.Text(), nullable=False),
        sa.Column("contract_version", sa.Integer(), nullable=False),
        sa.Column("compiler_revision", sa.Text(), nullable=False),
        sa.Column("prompt_revision", sa.Text(), nullable=False),
        sa.Column("family", sa.Text(), nullable=False),
        sa.Column("motif_count", sa.Integer(), nullable=False),
        sa.Column("retrieval_text", sa.Text(), nullable=False),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("structural_fingerprint", sa.Text(), nullable=True),
        sa.Column("source_digest", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column("embedding_vertex", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("nearest_kind", sa.Text(), nullable=True),
        sa.Column("nearest_id", sa.Text(), nullable=True),
        sa.Column("nearest_similarity", sa.REAL(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column(
            "rule_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("review_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("approved_example_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "family IN ('solid', 'stripe', 'lattice', 'scatter', 'path', 'point_set', 'stripe_motif', 'multi_motif')",
            name=op.f("ck_authoring_promotion_candidates_family"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'hold', 'rejected', 'approved', 'duplicate', 'invalid')",
            name=op.f("ck_authoring_promotion_candidates_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('pending', 'hold', 'approved') OR (embedding_model IS NOT NULL AND embedding_vertex IS NOT NULL AND structural_fingerprint IS NOT NULL)",
            name=op.f("ck_authoring_promotion_candidates_reviewable_ready"),
        ),
        sa.CheckConstraint(
            "contract_version > 0",
            name=op.f("ck_authoring_promotion_candidates_contract_version_positive"),
        ),
        sa.CheckConstraint(
            "motif_count BETWEEN 0 AND 2",
            name=op.f("ck_authoring_promotion_candidates_motif_count"),
        ),
        sa.CheckConstraint(
            "nearest_similarity IS NULL OR nearest_similarity BETWEEN -1 AND 1",
            name=op.f("ck_authoring_promotion_candidates_nearest_similarity"),
        ),
        sa.CheckConstraint(
            "plan_index >= 0", name=op.f("ck_authoring_promotion_candidates_plan_index")
        ),
        sa.CheckConstraint(
            "review_version >= 0", name=op.f("ck_authoring_promotion_candidates_review_version")
        ),
        sa.ForeignKeyConstraint(
            ["approved_example_id"],
            ["authoring_examples.id"],
            name=op.f("fk_authoring_promotion_candidates_approved_example_id_authoring_examples"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_authoring_promotion_candidates_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_generation_log_id"],
            ["seamless_generation_logs.id"],
            name=op.f(
                "fk_authoring_promotion_candidates_source_generation_log_id_seamless_generation_logs"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authoring_promotion_candidates")),
        sa.UniqueConstraint(
            "approved_example_id",
            name=op.f("uq_authoring_promotion_candidates_approved_example_id"),
        ),
        sa.UniqueConstraint(
            "source_key", name=op.f("uq_authoring_promotion_candidates_source_key")
        ),
    )
    op.create_index(
        "ix_authoring_promotion_candidates_fingerprint_status",
        "authoring_promotion_candidates",
        ["structural_fingerprint", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authoring_promotion_candidates_source_generation_log_id"),
        "authoring_promotion_candidates",
        ["source_generation_log_id"],
        unique=False,
    )
    op.create_index(
        "ix_authoring_promotion_candidates_status_created",
        "authoring_promotion_candidates",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.Column("item_type", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("selected_option_id", sa.Text(), nullable=True),
        sa.Column("reform_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("applied_user_coupon_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_type IN ('product', 'reform')", name=op.f("ck_cart_items_item_type")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cart_items_quantity")),
        sa.ForeignKeyConstraint(
            ["applied_user_coupon_id"],
            ["user_coupons.id"],
            name=op.f("fk_cart_items_applied_user_coupon_id_user_coupons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_cart_items_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cart_items_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("user_id", "item_id", name=op.f("uq_cart_items_user_id_item_id")),
    )
    op.create_table(
        "design_session_turns",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["design_sessions.id"],
            name=op.f("fk_design_session_turns_session_id_design_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_session_turns")),
        sa.UniqueConstraint(
            "session_id", "seq", name=op.f("uq_design_session_turns_session_id_seq")
        ),
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('finalize', 'export')", name=op.f("ck_generation_jobs_kind")),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'succeeded', 'failed', 'canceled')",
            name=op.f("ck_generation_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["design_sessions.id"],
            name=op.f("fk_generation_jobs_session_id_design_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_generation_jobs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
    )
    op.create_index(
        "ix_generation_jobs_status_created",
        "generation_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_jobs_user_id"), "generation_jobs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_generation_jobs_user_kind_created",
        "generation_jobs",
        ["user_id", "kind", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.Text(), nullable=False),
        sa.Column("order_type", sa.Text(), server_default="sale", nullable=False),
        sa.Column("status", sa.Text(), server_default="대기중", nullable=False),
        sa.Column("shipping_address_id", sa.Uuid(), nullable=True),
        sa.Column(
            "shipping_address_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("total_price", sa.Integer(), nullable=False),
        sa.Column("original_price", sa.Integer(), nullable=False),
        sa.Column("total_discount", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("shipping_cost", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("payment_group_id", sa.Uuid(), nullable=True),
        sa.Column("payment_key", sa.Text(), nullable=True),
        sa.Column("courier_company", sa.Text(), nullable=True),
        sa.Column("tracking_number", sa.Text(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("company_courier_company", sa.Text(), nullable=True),
        sa.Column("company_tracking_number", sa.Text(), nullable=True),
        sa.Column("company_shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "order_type IN ('sale', 'custom', 'repair', 'token', 'sample')",
            name=op.f("ck_orders_order_type"),
        ),
        sa.CheckConstraint(
            "status IN ('대기중', '결제중', '진행중', '배송중', '배송완료', '완료', '취소', '실패', '접수', '제작중', '제작완료', '수선중', '수선완료', '발송대기', '발송중', '발송확인중', '수거예정')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint("original_price >= 0", name=op.f("ck_orders_original_price")),
        sa.CheckConstraint("shipping_cost >= 0", name=op.f("ck_orders_shipping_cost")),
        sa.CheckConstraint("total_discount >= 0", name=op.f("ck_orders_total_discount")),
        sa.CheckConstraint("total_price >= 0", name=op.f("ck_orders_total_price")),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"],
            ["shipping_addresses.id"],
            name=op.f("fk_orders_shipping_address_id_shipping_addresses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
    )
    op.create_index(
        "ix_orders_admin_list", "orders", ["status", "order_type", "created_at", "id"], unique=False
    )
    op.create_index(
        op.f("ix_orders_payment_group_id"), "orders", ["payment_group_id"], unique=False
    )
    op.create_index(
        "ix_orders_pending_confirm_shipping",
        "orders",
        ["shipped_at"],
        unique=False,
        postgresql_where=sa.text("status = '배송중'"),
    )
    op.create_index(
        "ix_orders_pending_confirmation",
        "orders",
        ["delivered_at"],
        unique=False,
        postgresql_where=sa.text("status = '배송완료'"),
    )
    op.create_index(
        "ix_orders_stale_pending_created_at",
        "orders",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = '대기중'"),
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "quote_requests",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("quote_number", sa.Text(), nullable=False),
        sa.Column("shipping_address_id", sa.Uuid(), nullable=True),
        sa.Column(
            "shipping_address_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("additional_notes", sa.Text(), server_default="", nullable=False),
        sa.Column("contact_name", sa.Text(), nullable=False),
        sa.Column("business_name", sa.Text(), server_default="", nullable=False),
        sa.Column("contact_method", sa.Text(), nullable=False),
        sa.Column("contact_value", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="요청", nullable=False),
        sa.Column("quoted_amount", sa.Integer(), nullable=True),
        sa.Column("quote_conditions", sa.Text(), nullable=True),
        sa.Column("admin_memo", sa.Text(), nullable=True),
        sa.Column(
            "reference_images",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "contact_method IN ('email', 'phone')", name=op.f("ck_quote_requests_contact_method")
        ),
        sa.CheckConstraint(
            "status IN ('요청', '견적발송', '협의중', '확정', '종료')",
            name=op.f("ck_quote_requests_status"),
        ),
        sa.CheckConstraint("quantity >= 100", name=op.f("ck_quote_requests_quantity")),
        sa.CheckConstraint(
            "quoted_amount IS NULL OR quoted_amount >= 0",
            name=op.f("ck_quote_requests_quoted_amount"),
        ),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"],
            ["shipping_addresses.id"],
            name=op.f("fk_quote_requests_shipping_address_id_shipping_addresses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_quote_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_requests")),
        sa.UniqueConstraint("quote_number", name=op.f("uq_quote_requests_quote_number")),
    )
    op.create_index(
        "ix_quote_requests_admin_list",
        "quote_requests",
        ["status", "created_at", "id"],
        unique=False,
    )
    op.create_index(op.f("ix_quote_requests_user_id"), "quote_requests", ["user_id"], unique=False)
    op.create_table(
        "seamless_generation_attachments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("log_id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.Text(), server_default="auto", nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('auto', 'color_mood', 'motif', 'composition')",
            name=op.f("ck_seamless_generation_attachments_purpose"),
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
            name=op.f("fk_seamless_generation_attachments_image_id_images"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["log_id"],
            ["seamless_generation_logs.id"],
            name=op.f("fk_seamless_generation_attachments_log_id_seamless_generation_logs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seamless_generation_attachments")),
    )
    op.create_index(
        op.f("ix_seamless_generation_attachments_image_id"),
        "seamless_generation_attachments",
        ["image_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seamless_generation_attachments_log_id"),
        "seamless_generation_attachments",
        ["log_id"],
        unique=False,
    )
    op.create_index(
        "uq_seamless_generation_attachments_log_ordinal",
        "seamless_generation_attachments",
        ["log_id", "ordinal"],
        unique=True,
    )
    op.create_table(
        "design_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("token_class", sa.Text(), nullable=False),
        sa.Column("request_type", sa.Text(), nullable=True),
        sa.Column("ai_model", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("work_id", sa.Text(), nullable=True),
        sa.Column("source_order_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "request_type IS NULL OR request_type IN ('analysis', 'prep', 'render_standard', 'render_high')",
            name=op.f("ck_design_tokens_request_type"),
        ),
        sa.CheckConstraint(
            "token_class IN ('paid', 'bonus', 'free')", name=op.f("ck_design_tokens_token_class")
        ),
        sa.CheckConstraint(
            "type IN ('grant', 'use', 'refund', 'admin', 'purchase')",
            name=op.f("ck_design_tokens_type"),
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_design_tokens_amount")),
        sa.ForeignKeyConstraint(
            ["source_order_id"], ["orders.id"], name=op.f("fk_design_tokens_source_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_design_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_tokens")),
    )
    op.create_index(
        "ix_design_tokens_source_order_id",
        "design_tokens",
        ["source_order_id"],
        unique=False,
        postgresql_where=sa.text("source_order_id IS NOT NULL"),
    )
    op.create_index(
        "ix_design_tokens_user_class", "design_tokens", ["user_id", "token_class"], unique=False
    )
    op.create_index(
        "ix_design_tokens_user_created", "design_tokens", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_design_tokens_user_paid_expiry",
        "design_tokens",
        ["user_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("token_class = 'paid' AND expires_at IS NOT NULL"),
    )
    op.create_index(
        "uq_design_tokens_work_id",
        "design_tokens",
        ["work_id"],
        unique=True,
        postgresql_where=sa.text("work_id IS NOT NULL"),
    )
    op.create_table(
        "design_turn_attachments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=True),
        sa.Column("motif_id", sa.Text(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'photo' AND purpose IS NOT NULL AND purpose IN ('auto', 'color_mood', 'motif', 'composition')) OR (kind = 'svg' AND purpose IS NULL)",
            name=op.f("ck_design_turn_attachments_purpose"),
        ),
        sa.CheckConstraint(
            "kind IN ('photo', 'svg')", name=op.f("ck_design_turn_attachments_kind")
        ),
        sa.CheckConstraint(
            "(image_id IS NOT NULL)::int + (motif_id IS NOT NULL)::int = 1",
            name=op.f("ck_design_turn_attachments_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
            name=op.f("fk_design_turn_attachments_image_id_images"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["motif_id"], ["motifs.id"], name=op.f("fk_design_turn_attachments_motif_id_motifs")
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["design_session_turns.id"],
            name=op.f("fk_design_turn_attachments_turn_id_design_session_turns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_turn_attachments")),
        sa.UniqueConstraint(
            "turn_id", "ordinal", name=op.f("uq_design_turn_attachments_turn_id_ordinal")
        ),
    )
    op.create_index(
        op.f("ix_design_turn_attachments_turn_id"),
        "design_turn_attachments",
        ["turn_id"],
        unique=False,
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.Column("item_type", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("selected_option_id", sa.Text(), nullable=True),
        sa.Column(
            "item_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column("discount_amount", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "line_discount_amount", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("applied_user_coupon_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_type IN ('product', 'reform', 'custom', 'token', 'sample')",
            name=op.f("ck_order_items_item_type"),
        ),
        sa.CheckConstraint("discount_amount >= 0", name=op.f("ck_order_items_discount_amount")),
        sa.CheckConstraint(
            "line_discount_amount >= 0", name=op.f("ck_order_items_line_discount_amount")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_order_items_unit_price")),
        sa.ForeignKeyConstraint(
            ["applied_user_coupon_id"],
            ["user_coupons.id"],
            name=op.f("fk_order_items_applied_user_coupon_id_user_coupons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "order_status_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("previous_status", sa.Text(), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("is_rollback", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_order_status_logs_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_logs_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_logs")),
    )
    op.create_index(
        op.f("ix_order_status_logs_order_id"), "order_status_logs", ["order_id"], unique=False
    )
    op.create_table(
        "quote_request_status_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("quote_request_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("previous_status", sa.Text(), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_quote_request_status_logs_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quote_request_id"],
            ["quote_requests.id"],
            name=op.f("fk_quote_request_status_logs_quote_request_id_quote_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_request_status_logs")),
    )
    op.create_index(
        op.f("ix_quote_request_status_logs_quote_request_id"),
        "quote_request_status_logs",
        ["quote_request_id"],
        unique=False,
    )
    op.create_table(
        "repair_pickup_requests",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_name", sa.Text(), nullable=False),
        sa.Column("recipient_phone", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("detail_address", sa.Text(), nullable=True),
        sa.Column("pickup_fee", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pickup_fee >= 0", name=op.f("ck_repair_pickup_requests_pickup_fee")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_repair_pickup_requests_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repair_pickup_requests")),
        sa.UniqueConstraint("order_id", name=op.f("uq_repair_pickup_requests_order_id")),
    )
    op.create_table(
        "repair_shipping_receipts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_type", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "photos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IS NULL OR reason IN ('quick', 'overseas', 'lost')",
            name=op.f("ck_repair_shipping_receipts_reason"),
        ),
        sa.CheckConstraint(
            "receipt_type IN ('tracking', 'no_tracking')",
            name=op.f("ck_repair_shipping_receipts_receipt_type"),
        ),
        sa.CheckConstraint(
            "memo IS NULL OR char_length(memo) <= 500",
            name=op.f("ck_repair_shipping_receipts_memo_length"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_repair_shipping_receipts_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repair_shipping_receipts")),
    )
    op.create_index(
        op.f("ix_repair_shipping_receipts_order_id"),
        "repair_shipping_receipts",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("claim_number", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="접수", nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("return_courier_company", sa.Text(), nullable=True),
        sa.Column("return_tracking_number", sa.Text(), nullable=True),
        sa.Column("resend_courier_company", sa.Text(), nullable=True),
        sa.Column("resend_tracking_number", sa.Text(), nullable=True),
        sa.Column("refund_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('접수', '처리중', '수거요청', '수거완료', '재발송', '완료', '거부')",
            name=op.f("ck_claims_status"),
        ),
        sa.CheckConstraint(
            "type IN ('cancel', 'return', 'exchange', 'token_refund')", name=op.f("ck_claims_type")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_claims_quantity")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_claims_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"], ["order_items.id"], name=op.f("fk_claims_order_item_id_order_items")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_claims_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("claim_number", name=op.f("uq_claims_claim_number")),
    )
    op.create_index(
        "ix_claims_admin_list", "claims", ["status", "type", "created_at", "id"], unique=False
    )
    op.create_index(op.f("ix_claims_user_id"), "claims", ["user_id"], unique=False)
    op.create_index(
        "uq_claims_active_per_item",
        "claims",
        ["order_item_id", "type"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('접수', '처리중', '수거요청', '수거완료', '재발송', '완료')"
        ),
    )
    op.create_index(
        "uq_claims_single_active_per_order",
        "claims",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('접수', '처리중', '수거요청', '수거완료', '재발송')"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("order_type", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "photos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "order_type IN ('sale', 'repair', 'custom', 'sample')",
            name=op.f("ck_reviews_order_type"),
        ),
        sa.CheckConstraint(
            "char_length(content) BETWEEN 1 AND 1000", name=op.f("ck_reviews_content_length")
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_reviews_rating")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_reviews_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_reviews_order_item_id_order_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_reviews_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reviews_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint(
            "order_id",
            "order_item_id",
            name="uq_reviews_order_item",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_reviews_product_id"), "reviews", ["product_id"], unique=False)
    op.create_index(
        "ix_reviews_public_list", "reviews", ["order_type", "created_at", "id"], unique=False
    )
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "claim_notification_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("delivery_status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_status IN ('pending', 'sent', 'failed', 'skipped')",
            name=op.f("ck_claim_notification_logs_delivery_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_claim_notification_logs_attempts")),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_notification_logs_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_notification_logs")),
        sa.UniqueConstraint(
            "claim_id", "status", name=op.f("uq_claim_notification_logs_claim_id_status")
        ),
    )
    op.create_index(
        "ix_claim_notification_logs_delivery",
        "claim_notification_logs",
        ["delivery_status", "created_at"],
        unique=False,
    )
    op.create_table(
        "claim_status_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("previous_status", sa.Text(), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("is_rollback", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_claim_status_logs_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_status_logs_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_status_logs")),
    )
    op.create_index(
        op.f("ix_claim_status_logs_claim_id"), "claim_status_logs", ["claim_id"], unique=False
    )
    op.create_table(
        "payment_incidents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("operation_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("expected_amount", sa.Integer(), nullable=False),
        sa.Column("observed_amount", sa.Integer(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("resolution_memo", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved')", name=op.f("ck_payment_incidents_status")
        ),
        sa.CheckConstraint(
            "type IN ('confirm', 'refund', 'partial_cancel', 'mixed_state', 'amount_mismatch')",
            name=op.f("ck_payment_incidents_type"),
        ),
        sa.CheckConstraint(
            "expected_amount >= 0", name=op.f("ck_payment_incidents_expected_amount")
        ),
        sa.CheckConstraint(
            "observed_amount IS NULL OR observed_amount >= 0",
            name=op.f("ck_payment_incidents_observed_amount"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_payment_incidents_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_payment_incidents_claim_id_claims"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payment_incidents_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_payment_incidents_resolved_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_incidents")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_payment_incidents_operation_id")),
    )
    op.create_index(
        "ix_payment_incidents_claim_id", "payment_incidents", ["claim_id"], unique=False
    )
    op.create_index(
        "ix_payment_incidents_order_id", "payment_incidents", ["order_id"], unique=False
    )
    op.create_index(
        "ix_payment_incidents_queue",
        "payment_incidents",
        ["status", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payment_incidents_queue", table_name="payment_incidents")
    op.drop_index("ix_payment_incidents_order_id", table_name="payment_incidents")
    op.drop_index("ix_payment_incidents_claim_id", table_name="payment_incidents")
    op.drop_table("payment_incidents")
    op.drop_index(op.f("ix_claim_status_logs_claim_id"), table_name="claim_status_logs")
    op.drop_table("claim_status_logs")
    op.drop_index("ix_claim_notification_logs_delivery", table_name="claim_notification_logs")
    op.drop_table("claim_notification_logs")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index("ix_reviews_public_list", table_name="reviews")
    op.drop_index(op.f("ix_reviews_product_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(
        "uq_claims_single_active_per_order",
        table_name="claims",
        postgresql_where=sa.text("status IN ('접수', '처리중', '수거요청', '수거완료', '재발송')"),
    )
    op.drop_index(
        "uq_claims_active_per_item",
        table_name="claims",
        postgresql_where=sa.text(
            "status IN ('접수', '처리중', '수거요청', '수거완료', '재발송', '완료')"
        ),
    )
    op.drop_index(op.f("ix_claims_user_id"), table_name="claims")
    op.drop_index("ix_claims_admin_list", table_name="claims")
    op.drop_table("claims")
    op.drop_index(
        op.f("ix_repair_shipping_receipts_order_id"), table_name="repair_shipping_receipts"
    )
    op.drop_table("repair_shipping_receipts")
    op.drop_table("repair_pickup_requests")
    op.drop_index(
        op.f("ix_quote_request_status_logs_quote_request_id"),
        table_name="quote_request_status_logs",
    )
    op.drop_table("quote_request_status_logs")
    op.drop_index(op.f("ix_order_status_logs_order_id"), table_name="order_status_logs")
    op.drop_table("order_status_logs")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_design_turn_attachments_turn_id"), table_name="design_turn_attachments")
    op.drop_table("design_turn_attachments")
    op.drop_index(
        "uq_design_tokens_work_id",
        table_name="design_tokens",
        postgresql_where=sa.text("work_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_design_tokens_user_paid_expiry",
        table_name="design_tokens",
        postgresql_where=sa.text("token_class = 'paid' AND expires_at IS NOT NULL"),
    )
    op.drop_index("ix_design_tokens_user_created", table_name="design_tokens")
    op.drop_index("ix_design_tokens_user_class", table_name="design_tokens")
    op.drop_index(
        "ix_design_tokens_source_order_id",
        table_name="design_tokens",
        postgresql_where=sa.text("source_order_id IS NOT NULL"),
    )
    op.drop_table("design_tokens")
    op.drop_index(
        "uq_seamless_generation_attachments_log_ordinal",
        table_name="seamless_generation_attachments",
    )
    op.drop_index(
        op.f("ix_seamless_generation_attachments_log_id"),
        table_name="seamless_generation_attachments",
    )
    op.drop_index(
        op.f("ix_seamless_generation_attachments_image_id"),
        table_name="seamless_generation_attachments",
    )
    op.drop_table("seamless_generation_attachments")
    op.drop_index(op.f("ix_quote_requests_user_id"), table_name="quote_requests")
    op.drop_index("ix_quote_requests_admin_list", table_name="quote_requests")
    op.drop_table("quote_requests")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(
        "ix_orders_stale_pending_created_at",
        table_name="orders",
        postgresql_where=sa.text("status = '대기중'"),
    )
    op.drop_index(
        "ix_orders_pending_confirmation",
        table_name="orders",
        postgresql_where=sa.text("status = '배송완료'"),
    )
    op.drop_index(
        "ix_orders_pending_confirm_shipping",
        table_name="orders",
        postgresql_where=sa.text("status = '배송중'"),
    )
    op.drop_index(op.f("ix_orders_payment_group_id"), table_name="orders")
    op.drop_index("ix_orders_admin_list", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_generation_jobs_user_kind_created", table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_user_id"), table_name="generation_jobs")
    op.drop_index("ix_generation_jobs_status_created", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_table("design_session_turns")
    op.drop_table("cart_items")
    op.drop_index(
        "ix_authoring_promotion_candidates_status_created",
        table_name="authoring_promotion_candidates",
    )
    op.drop_index(
        op.f("ix_authoring_promotion_candidates_source_generation_log_id"),
        table_name="authoring_promotion_candidates",
    )
    op.drop_index(
        "ix_authoring_promotion_candidates_fingerprint_status",
        table_name="authoring_promotion_candidates",
    )
    op.drop_table("authoring_promotion_candidates")
    op.drop_index(op.f("ix_user_motifs_user_id"), table_name="user_motifs")
    op.drop_table("user_motifs")
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_table("user_coupons")
    op.drop_index(op.f("ix_token_purchases_user_id"), table_name="token_purchases")
    op.drop_table("token_purchases")
    op.drop_index(op.f("ix_shipping_addresses_user_id"), table_name="shipping_addresses")
    op.drop_table("shipping_addresses")
    op.drop_index("ix_refresh_tokens_user_id_session_kind", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_product_options_product_id"), table_name="product_options")
    op.drop_table("product_options")
    op.drop_index(op.f("ix_product_likes_product_id"), table_name="product_likes")
    op.drop_table("product_likes")
    op.drop_table("pricing_constants")
    op.drop_index(op.f("ix_phone_verifications_user_id"), table_name="phone_verifications")
    op.drop_table("phone_verifications")
    op.drop_index(
        op.f("ix_notification_preference_logs_user_id"), table_name="notification_preference_logs"
    )
    op.drop_table("notification_preference_logs")
    op.drop_index(op.f("ix_inquiries_user_id"), table_name="inquiries")
    op.drop_index("ix_inquiries_public_list", table_name="inquiries")
    op.drop_index(op.f("ix_inquiries_product_id"), table_name="inquiries")
    op.drop_index("ix_inquiries_admin_list", table_name="inquiries")
    op.drop_table("inquiries")
    op.drop_index(
        "uq_images_repair_shipping_upload",
        table_name="images",
        postgresql_where=sa.text("entity_type = 'repair_shipping_upload'"),
    )
    op.drop_index(
        "uq_images_reform_upload",
        table_name="images",
        postgresql_where=sa.text("entity_type = 'reform_upload'"),
    )
    op.drop_index(
        "ix_images_expires",
        table_name="images",
        postgresql_where=sa.text("expires_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index("ix_images_entity", table_name="images")
    op.drop_index(
        "ix_images_deletion_claimed",
        table_name="images",
        postgresql_where=sa.text("deletion_claimed_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_table("images")
    op.drop_index(op.f("ix_design_sessions_user_id"), table_name="design_sessions")
    op.drop_table("design_sessions")
    op.drop_index(
        "uq_authoring_examples_active_fingerprint",
        table_name="authoring_examples",
        postgresql_where=sa.text("active"),
    )
    op.drop_index("ix_authoring_examples_active_family", table_name="authoring_examples")
    op.drop_table("authoring_examples")
    op.drop_table("admin_settings")
    op.drop_index("ix_admin_operation_logs_created_at", table_name="admin_operation_logs")
    op.drop_index(op.f("ix_admin_operation_logs_actor_id"), table_name="admin_operation_logs")
    op.drop_table("admin_operation_logs")
    op.drop_index(
        "uq_users_email", table_name="users", postgresql_where=sa.text("email IS NOT NULL")
    )
    op.drop_table("users")
    op.drop_table("seamless_generation_logs")
    op.drop_index("ix_products_admin_list", table_name="products")
    op.drop_table("products")
    op.drop_index(
        "ix_motifs_embedding_vertex_halfvec_hnsw",
        table_name="motifs",
        postgresql_using="hnsw",
        postgresql_ops={"embedding_vertex_halfvec": "halfvec_cosine_ops"},
    )
    op.drop_table("motifs")
    op.drop_index("ix_manual_orders_admin_list", table_name="manual_orders")
    op.drop_table("manual_orders")
    op.drop_index("ix_coupons_admin_list", table_name="coupons")
    op.drop_table("coupons")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP EXTENSION IF EXISTS vector")
