"""baseline

Revision ID: a658f96021f4
Revises:
Create Date: 2026-07-06 14:17:45.157841

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a658f96021f4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupons",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("discount_type", sa.Text(), nullable=False),
        sa.Column("discount_value", sa.Numeric(), nullable=False),
        sa.Column("max_discount_amount", sa.Numeric(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_type IN ('percentage', 'fixed')", name=op.f("ck_coupons_discount_type")
        ),
        sa.CheckConstraint("discount_value > 0", name=op.f("ck_coupons_discount_value")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
        sa.UniqueConstraint("name", name=op.f("uq_coupons_name")),
    )
    op.create_table(
        "motifs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column(
            "color_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[\"s0\"]'::jsonb"),
            nullable=False,
        ),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("anchor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("view", sa.Text(), nullable=True),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("style", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column("source", sa.Text(), server_default="recraft", nullable=False),
        sa.Column("quality", sa.REAL(), nullable=True),
        sa.Column("variant_group", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope IS NULL OR scope IN ('whole', 'partial')", name=op.f("ck_motifs_scope")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_motifs")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("material", sa.Text(), nullable=False),
        sa.Column("info", sa.Text(), nullable=False),
        sa.Column("detail_images", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("option_label", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('3fold', 'sfolderato', 'knit', 'bowtie')",
            name=op.f("ck_products_category"),
        ),
        sa.CheckConstraint(
            "color IN ('black', 'navy', 'gray', 'wine', 'blue', 'brown', 'beige', 'silver')",
            name=op.f("ck_products_color"),
        ),
        sa.CheckConstraint(
            "material IN ('silk', 'cotton', 'polyester', 'wool')", name=op.f("ck_products_material")
        ),
        sa.CheckConstraint(
            "pattern IN ('solid', 'stripe', 'dot', 'check', 'paisley')",
            name=op.f("ck_products_pattern"),
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_price")),
        sa.CheckConstraint("stock IS NULL OR stock >= 0", name=op.f("ck_products_stock")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("code", name=op.f("uq_products_code")),
    )
    op.create_table(
        "seamless_generation_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("input_type", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column(
            "has_reference_image", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("reference_image_bytes", sa.Integer(), nullable=True),
        sa.Column("colorway", sa.Text(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("candidate_count_requested", sa.Integer(), nullable=True),
        sa.Column("candidate_count_returned", sa.Integer(), nullable=True),
        sa.Column("distinct_layouts", sa.Integer(), nullable=True),
        sa.Column("available_strategies", sa.Integer(), nullable=True),
        sa.Column("engine_version", sa.Text(), nullable=True),
        sa.Column("registry_version", sa.Text(), nullable=True),
        sa.Column("intent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("generate_ms", sa.Numeric(), nullable=True),
        sa.Column("render_ms", sa.Numeric(), nullable=True),
        sa.Column("status", sa.Text(), server_default="success", nullable=False),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_type IN ('intent', 'prompt', 'reference_image')",
            name=op.f("ck_seamless_generation_logs_input_type"),
        ),
        sa.CheckConstraint(
            "status IN ('success', 'partial', 'error')",
            name=op.f("ck_seamless_generation_logs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seamless_generation_logs")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("customer", "admin", "manager", name="user_role"),
            server_default="customer",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("birth", sa.Date(), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "notification_consent", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "notification_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "marketing_kakao_sms_consent",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "admin_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_admin_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_admin_settings")),
    )
    op.create_table(
        "design_sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("colorway", sa.Text(), nullable=True),
        sa.Column("registry_version", sa.Text(), nullable=True),
        sa.Column("current_intent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recraft_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("finalize_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'finalized')", name=op.f("ck_design_sessions_status")
        ),
        sa.CheckConstraint("finalize_used >= 0", name=op.f("ck_design_sessions_finalize_used")),
        sa.CheckConstraint("recraft_used >= 0", name=op.f("ck_design_sessions_recraft_used")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_design_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_sessions")),
    )
    op.create_index(
        op.f("ix_design_sessions_user_id"), "design_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_images_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
    )
    op.create_index(
        "ix_images_deletion_claimed",
        "images",
        ["deletion_claimed_at"],
        unique=False,
        postgresql_where=sa.text("deletion_claimed_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index("ix_images_entity", "images", ["entity_type", "entity_id"], unique=False)
    op.create_index(
        "ix_images_expires",
        "images",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "uq_images_reform_upload",
        "images",
        ["entity_type", "entity_id"],
        unique=True,
        postgresql_where=sa.text("entity_type = 'reform_upload'"),
    )
    op.create_index(
        "uq_images_repair_shipping_upload",
        "images",
        ["entity_type", "entity_id"],
        unique=True,
        postgresql_where=sa.text("entity_type = 'repair_shipping_upload'"),
    )
    op.create_table(
        "inquiries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.Text(), server_default="일반", nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="답변대기", nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("answer_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('일반', '상품', '수선', '주문제작')", name=op.f("ck_inquiries_category")
        ),
        sa.CheckConstraint("status IN ('답변대기', '답변완료')", name=op.f("ck_inquiries_status")),
        sa.CheckConstraint(
            "char_length(content) BETWEEN 1 AND 5000", name=op.f("ck_inquiries_content_length")
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 200", name=op.f("ck_inquiries_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inquiries_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_inquiries_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inquiries")),
    )
    op.create_index(op.f("ix_inquiries_user_id"), "inquiries", ["user_id"], unique=False)
    op.create_table(
        "notification_preference_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("previous_notification_consent", sa.Boolean(), nullable=False),
        sa.Column("new_notification_consent", sa.Boolean(), nullable=False),
        sa.Column("previous_notification_enabled", sa.Boolean(), nullable=False),
        sa.Column("new_notification_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preference_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preference_logs")),
    )
    op.create_index(
        op.f("ix_notification_preference_logs_user_id"),
        "notification_preference_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "phone_verifications",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_phone_verifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_verifications")),
    )
    op.create_index(
        op.f("ix_phone_verifications_user_id"), "phone_verifications", ["user_id"], unique=False
    )
    op.create_table(
        "pricing_constants",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "category IN ('custom_order', 'fabric', 'reform', 'token', 'sample_discount')",
            name=op.f("ck_pricing_constants_category"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_pricing_constants_amount")),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_pricing_constants_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_pricing_constants")),
    )
    op.create_table(
        "product_likes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_likes_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_product_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_likes")),
        sa.UniqueConstraint(
            "user_id", "product_id", name=op.f("uq_product_likes_user_id_product_id")
        ),
    )
    op.create_index(
        op.f("ix_product_likes_product_id"), "product_likes", ["product_id"], unique=False
    )
    op.create_table(
        "product_options",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("additional_price", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("stock IS NULL OR stock >= 0", name=op.f("ck_product_options_stock")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_options_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_options")),
    )
    op.create_index(
        op.f("ix_product_options_product_id"), "product_options", ["product_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "shipping_addresses",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_name", sa.Text(), nullable=False),
        sa.Column("recipient_phone", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("address_detail", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("delivery_memo", sa.Text(), nullable=True),
        sa.Column("delivery_request", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_shipping_addresses_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipping_addresses")),
    )
    op.create_index(
        op.f("ix_shipping_addresses_user_id"), "shipping_addresses", ["user_id"], unique=False
    )
    op.create_table(
        "token_purchases",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("payment_group_id", sa.Uuid(), nullable=False),
        sa.Column("plan_key", sa.Text(), nullable=False),
        sa.Column("token_amount", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="대기중", nullable=False),
        sa.Column("payment_key", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plan_key IN ('starter', 'popular', 'pro')", name=op.f("ck_token_purchases_plan_key")
        ),
        sa.CheckConstraint(
            "status IN ('대기중', '결제중', '완료', '실패')", name=op.f("ck_token_purchases_status")
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_token_purchases_price")),
        sa.CheckConstraint("token_amount > 0", name=op.f("ck_token_purchases_token_amount")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_token_purchases_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_purchases")),
        sa.UniqueConstraint("payment_group_id", name=op.f("uq_token_purchases_payment_group_id")),
    )
    op.create_index(
        op.f("ix_token_purchases_user_id"), "token_purchases", ["user_id"], unique=False
    )
    op.create_table(
        "user_coupons",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("coupon_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'used', 'expired', 'revoked', 'reserved')",
            name=op.f("ck_user_coupons_status"),
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"], ["coupons.id"], name=op.f("fk_user_coupons_coupon_id_coupons")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_coupons_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_coupons")),
        sa.UniqueConstraint("user_id", "coupon_id", name=op.f("uq_user_coupons_user_id_coupon_id")),
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_user_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('google', 'kakao', 'apple', 'naver')",
            name=op.f("ck_user_identities_provider"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint(
            "provider",
            "provider_user_id",
            name=op.f("uq_user_identities_provider_provider_user_id"),
        ),
    )
    op.create_index(
        op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.Column("item_type", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("selected_option_id", sa.Text(), nullable=True),
        sa.Column("reform_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("applied_user_coupon_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_type IN ('product', 'reform')", name=op.f("ck_cart_items_item_type")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cart_items_quantity")),
        sa.ForeignKeyConstraint(
            ["applied_user_coupon_id"],
            ["user_coupons.id"],
            name=op.f("fk_cart_items_applied_user_coupon_id_user_coupons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_cart_items_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cart_items_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("user_id", "item_id", name=op.f("uq_cart_items_user_id_item_id")),
    )
    op.create_table(
        "design_session_turns",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["design_sessions.id"],
            name=op.f("fk_design_session_turns_session_id_design_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_session_turns")),
        sa.UniqueConstraint(
            "session_id", "seq", name=op.f("uq_design_session_turns_session_id_seq")
        ),
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('finalize', 'export')", name=op.f("ck_generation_jobs_kind")),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'succeeded', 'failed')",
            name=op.f("ck_generation_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["design_sessions.id"],
            name=op.f("fk_generation_jobs_session_id_design_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_generation_jobs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
    )
    op.create_index(
        "ix_generation_jobs_status_created",
        "generation_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_jobs_user_id"), "generation_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.Text(), nullable=False),
        sa.Column("order_type", sa.Text(), server_default="sale", nullable=False),
        sa.Column("status", sa.Text(), server_default="대기중", nullable=False),
        sa.Column("shipping_address_id", sa.Uuid(), nullable=True),
        sa.Column("total_price", sa.Integer(), nullable=False),
        sa.Column("original_price", sa.Integer(), nullable=False),
        sa.Column("total_discount", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("shipping_cost", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("payment_group_id", sa.Uuid(), nullable=True),
        sa.Column("payment_key", sa.Text(), nullable=True),
        sa.Column("courier_company", sa.Text(), nullable=True),
        sa.Column("tracking_number", sa.Text(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("company_courier_company", sa.Text(), nullable=True),
        sa.Column("company_tracking_number", sa.Text(), nullable=True),
        sa.Column("company_shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "order_type IN ('sale', 'custom', 'repair', 'token', 'sample')",
            name=op.f("ck_orders_order_type"),
        ),
        sa.CheckConstraint(
            "status IN ('대기중', '결제중', '진행중', '배송중', '배송완료', '완료', '취소', '실패', '접수', '제작중', '제작완료', '수선중', '수선완료', '발송대기', '발송중', '발송확인중', '수거예정')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint("original_price >= 0", name=op.f("ck_orders_original_price")),
        sa.CheckConstraint("shipping_cost >= 0", name=op.f("ck_orders_shipping_cost")),
        sa.CheckConstraint("total_discount >= 0", name=op.f("ck_orders_total_discount")),
        sa.CheckConstraint("total_price >= 0", name=op.f("ck_orders_total_price")),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"],
            ["shipping_addresses.id"],
            name=op.f("fk_orders_shipping_address_id_shipping_addresses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
    )
    op.create_index(
        op.f("ix_orders_payment_group_id"), "orders", ["payment_group_id"], unique=False
    )
    op.create_index(
        "ix_orders_pending_confirm_shipping",
        "orders",
        ["shipped_at"],
        unique=False,
        postgresql_where=sa.text("status = '배송중'"),
    )
    op.create_index(
        "ix_orders_pending_confirmation",
        "orders",
        ["delivered_at"],
        unique=False,
        postgresql_where=sa.text("status = '배송완료'"),
    )
    op.create_index(
        "ix_orders_stale_pending_created_at",
        "orders",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = '대기중'"),
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "quote_requests",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("quote_number", sa.Text(), nullable=False),
        sa.Column("shipping_address_id", sa.Uuid(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("additional_notes", sa.Text(), server_default="", nullable=False),
        sa.Column("contact_name", sa.Text(), nullable=False),
        sa.Column("business_name", sa.Text(), server_default="", nullable=False),
        sa.Column("contact_method", sa.Text(), nullable=False),
        sa.Column("contact_value", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="요청", nullable=False),
        sa.Column("quoted_amount", sa.Integer(), nullable=True),
        sa.Column("quote_conditions", sa.Text(), nullable=True),
        sa.Column("admin_memo", sa.Text(), nullable=True),
        sa.Column(
            "reference_images",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "contact_method IN ('email', 'phone')", name=op.f("ck_quote_requests_contact_method")
        ),
        sa.CheckConstraint(
            "status IN ('요청', '견적발송', '협의중', '확정', '종료')",
            name=op.f("ck_quote_requests_status"),
        ),
        sa.CheckConstraint("quantity >= 100", name=op.f("ck_quote_requests_quantity")),
        sa.CheckConstraint(
            "quoted_amount IS NULL OR quoted_amount >= 0",
            name=op.f("ck_quote_requests_quoted_amount"),
        ),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"],
            ["shipping_addresses.id"],
            name=op.f("fk_quote_requests_shipping_address_id_shipping_addresses"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_quote_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_requests")),
        sa.UniqueConstraint("quote_number", name=op.f("uq_quote_requests_quote_number")),
    )
    op.create_index(op.f("ix_quote_requests_user_id"), "quote_requests", ["user_id"], unique=False)
    op.create_table(
        "design_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("token_class", sa.Text(), nullable=False),
        sa.Column("request_type", sa.Text(), nullable=True),
        sa.Column("ai_model", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("work_id", sa.Text(), nullable=True),
        sa.Column("source_order_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "request_type IS NULL OR request_type IN ('analysis', 'prep', 'render_standard', 'render_high')",
            name=op.f("ck_design_tokens_request_type"),
        ),
        sa.CheckConstraint(
            "token_class IN ('paid', 'bonus', 'free')", name=op.f("ck_design_tokens_token_class")
        ),
        sa.CheckConstraint(
            "type IN ('grant', 'use', 'refund', 'admin', 'purchase')",
            name=op.f("ck_design_tokens_type"),
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_design_tokens_amount")),
        sa.ForeignKeyConstraint(
            ["source_order_id"], ["orders.id"], name=op.f("fk_design_tokens_source_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_design_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_tokens")),
    )
    op.create_index(
        "ix_design_tokens_source_order_id",
        "design_tokens",
        ["source_order_id"],
        unique=False,
        postgresql_where=sa.text("source_order_id IS NOT NULL"),
    )
    op.create_index(
        "ix_design_tokens_user_class", "design_tokens", ["user_id", "token_class"], unique=False
    )
    op.create_index(
        "ix_design_tokens_user_created", "design_tokens", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_design_tokens_user_paid_expiry",
        "design_tokens",
        ["user_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("token_class = 'paid' AND expires_at IS NOT NULL"),
    )
    op.create_index(
        "uq_design_tokens_work_id",
        "design_tokens",
        ["work_id"],
        unique=True,
        postgresql_where=sa.text("work_id IS NOT NULL"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.Column("item_type", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("selected_option_id", sa.Text(), nullable=True),
        sa.Column("item_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column("discount_amount", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "line_discount_amount", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("applied_user_coupon_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_type IN ('product', 'reform', 'custom', 'token', 'sample')",
            name=op.f("ck_order_items_item_type"),
        ),
        sa.CheckConstraint("discount_amount >= 0", name=op.f("ck_order_items_discount_amount")),
        sa.CheckConstraint(
            "line_discount_amount >= 0", name=op.f("ck_order_items_line_discount_amount")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_order_items_unit_price")),
        sa.ForeignKeyConstraint(
            ["applied_user_coupon_id"],
            ["user_coupons.id"],
            name=op.f("fk_order_items_applied_user_coupon_id_user_coupons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "order_status_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("previous_status", sa.Text(), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("is_rollback", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_order_status_logs_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_logs_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_logs")),
    )
    op.create_index(
        op.f("ix_order_status_logs_order_id"), "order_status_logs", ["order_id"], unique=False
    )
    op.create_table(
        "quote_request_status_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("quote_request_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("previous_status", sa.Text(), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_quote_request_status_logs_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quote_request_id"],
            ["quote_requests.id"],
            name=op.f("fk_quote_request_status_logs_quote_request_id_quote_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_request_status_logs")),
    )
    op.create_index(
        op.f("ix_quote_request_status_logs_quote_request_id"),
        "quote_request_status_logs",
        ["quote_request_id"],
        unique=False,
    )
    op.create_table(
        "repair_pickup_requests",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_name", sa.Text(), nullable=False),
        sa.Column("recipient_phone", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("detail_address", sa.Text(), nullable=True),
        sa.Column("pickup_fee", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pickup_fee >= 0", name=op.f("ck_repair_pickup_requests_pickup_fee")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_repair_pickup_requests_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repair_pickup_requests")),
        sa.UniqueConstraint("order_id", name=op.f("uq_repair_pickup_requests_order_id")),
    )
    op.create_table(
        "repair_shipping_receipts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_type", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "photos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IS NULL OR reason IN ('quick', 'overseas', 'lost')",
            name=op.f("ck_repair_shipping_receipts_reason"),
        ),
        sa.CheckConstraint(
            "receipt_type IN ('tracking', 'no_tracking')",
            name=op.f("ck_repair_shipping_receipts_receipt_type"),
        ),
        sa.CheckConstraint(
            "memo IS NULL OR char_length(memo) <= 500",
            name=op.f("ck_repair_shipping_receipts_memo_length"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_repair_shipping_receipts_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repair_shipping_receipts")),
    )
    op.create_index(
        op.f("ix_repair_shipping_receipts_order_id"),
        "repair_shipping_receipts",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("claim_number", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="접수", nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("return_courier_company", sa.Text(), nullable=True),
        sa.Column("return_tracking_number", sa.Text(), nullable=True),
        sa.Column("resend_courier_company", sa.Text(), nullable=True),
        sa.Column("resend_tracking_number", sa.Text(), nullable=True),
        sa.Column("refund_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('접수', '처리중', '수거요청', '수거완료', '재발송', '완료', '거부')",
            name=op.f("ck_claims_status"),
        ),
        sa.CheckConstraint(
            "type IN ('cancel', 'return', 'exchange', 'token_refund')", name=op.f("ck_claims_type")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_claims_quantity")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_claims_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"], ["order_items.id"], name=op.f("fk_claims_order_item_id_order_items")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_claims_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("claim_number", name=op.f("uq_claims_claim_number")),
    )
    op.create_index(op.f("ix_claims_user_id"), "claims", ["user_id"], unique=False)
    op.create_index(
        "uq_claims_active_per_item",
        "claims",
        ["order_item_id", "type"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('접수', '처리중', '수거요청', '수거완료', '재발송', '완료')"
        ),
    )
    op.create_index(
        "uq_claims_single_active_per_order",
        "claims",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('접수', '처리중', '수거요청', '수거완료', '재발송')"),
    )
    op.create_table(
        "claim_notification_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_notification_logs_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_notification_logs")),
        sa.UniqueConstraint(
            "claim_id", "status", name=op.f("uq_claim_notification_logs_claim_id_status")
        ),
    )
    op.create_table(
        "claim_status_logs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("previous_status", sa.Text(), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("is_rollback", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_claim_status_logs_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_claim_status_logs_claim_id_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_status_logs")),
    )
    op.create_index(
        op.f("ix_claim_status_logs_claim_id"), "claim_status_logs", ["claim_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_claim_status_logs_claim_id"), table_name="claim_status_logs")
    op.drop_table("claim_status_logs")
    op.drop_table("claim_notification_logs")
    op.drop_index(
        "uq_claims_single_active_per_order",
        table_name="claims",
        postgresql_where=sa.text("status IN ('접수', '처리중', '수거요청', '수거완료', '재발송')"),
    )
    op.drop_index(
        "uq_claims_active_per_item",
        table_name="claims",
        postgresql_where=sa.text(
            "status IN ('접수', '처리중', '수거요청', '수거완료', '재발송', '완료')"
        ),
    )
    op.drop_index(op.f("ix_claims_user_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(
        op.f("ix_repair_shipping_receipts_order_id"), table_name="repair_shipping_receipts"
    )
    op.drop_table("repair_shipping_receipts")
    op.drop_table("repair_pickup_requests")
    op.drop_index(
        op.f("ix_quote_request_status_logs_quote_request_id"),
        table_name="quote_request_status_logs",
    )
    op.drop_table("quote_request_status_logs")
    op.drop_index(op.f("ix_order_status_logs_order_id"), table_name="order_status_logs")
    op.drop_table("order_status_logs")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(
        "uq_design_tokens_work_id",
        table_name="design_tokens",
        postgresql_where=sa.text("work_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_design_tokens_user_paid_expiry",
        table_name="design_tokens",
        postgresql_where=sa.text("token_class = 'paid' AND expires_at IS NOT NULL"),
    )
    op.drop_index("ix_design_tokens_user_created", table_name="design_tokens")
    op.drop_index("ix_design_tokens_user_class", table_name="design_tokens")
    op.drop_index(
        "ix_design_tokens_source_order_id",
        table_name="design_tokens",
        postgresql_where=sa.text("source_order_id IS NOT NULL"),
    )
    op.drop_table("design_tokens")
    op.drop_index(op.f("ix_quote_requests_user_id"), table_name="quote_requests")
    op.drop_table("quote_requests")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(
        "ix_orders_stale_pending_created_at",
        table_name="orders",
        postgresql_where=sa.text("status = '대기중'"),
    )
    op.drop_index(
        "ix_orders_pending_confirmation",
        table_name="orders",
        postgresql_where=sa.text("status = '배송완료'"),
    )
    op.drop_index(
        "ix_orders_pending_confirm_shipping",
        table_name="orders",
        postgresql_where=sa.text("status = '배송중'"),
    )
    op.drop_index(op.f("ix_orders_payment_group_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_generation_jobs_user_id"), table_name="generation_jobs")
    op.drop_index("ix_generation_jobs_status_created", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_table("design_session_turns")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_table("user_coupons")
    op.drop_index(op.f("ix_token_purchases_user_id"), table_name="token_purchases")
    op.drop_table("token_purchases")
    op.drop_index(op.f("ix_shipping_addresses_user_id"), table_name="shipping_addresses")
    op.drop_table("shipping_addresses")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_product_options_product_id"), table_name="product_options")
    op.drop_table("product_options")
    op.drop_index(op.f("ix_product_likes_product_id"), table_name="product_likes")
    op.drop_table("product_likes")
    op.drop_table("pricing_constants")
    op.drop_index(op.f("ix_phone_verifications_user_id"), table_name="phone_verifications")
    op.drop_table("phone_verifications")
    op.drop_index(
        op.f("ix_notification_preference_logs_user_id"), table_name="notification_preference_logs"
    )
    op.drop_table("notification_preference_logs")
    op.drop_index(op.f("ix_inquiries_user_id"), table_name="inquiries")
    op.drop_table("inquiries")
    op.drop_index(
        "uq_images_repair_shipping_upload",
        table_name="images",
        postgresql_where=sa.text("entity_type = 'repair_shipping_upload'"),
    )
    op.drop_index(
        "uq_images_reform_upload",
        table_name="images",
        postgresql_where=sa.text("entity_type = 'reform_upload'"),
    )
    op.drop_index(
        "ix_images_expires",
        table_name="images",
        postgresql_where=sa.text("expires_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index("ix_images_entity", table_name="images")
    op.drop_index(
        "ix_images_deletion_claimed",
        table_name="images",
        postgresql_where=sa.text("deletion_claimed_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_table("images")
    op.drop_index(op.f("ix_design_sessions_user_id"), table_name="design_sessions")
    op.drop_table("design_sessions")
    op.drop_table("admin_settings")
    op.drop_index(
        "uq_users_email", table_name="users", postgresql_where=sa.text("email IS NOT NULL")
    )
    op.drop_table("users")
    op.drop_table("seamless_generation_logs")
    op.drop_table("products")
    op.drop_table("motifs")
    op.drop_table("coupons")
    op.execute("DROP TYPE IF EXISTS user_role")
    # ### end Alembic commands ###
