// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminClaimStatusRequest
 */
export type AdminClaimStatusRequest = {
    /**
     * Is Rollback
     */
    is_rollback?: boolean;
    /**
     * Memo
     */
    memo?: string | null;
    /**
     * New Status
     */
    new_status: string;
};

/**
 * AdminClaimStatusResponse
 */
export type AdminClaimStatusResponse = {
    /**
     * New Status
     */
    new_status: string;
    /**
     * Previous Status
     */
    previous_status: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * AdminOrderOut
 */
export type AdminOrderOut = {
    /**
     * Admin Actions
     */
    admin_actions?: Array<string>;
    /**
     * Company Courier Company
     */
    company_courier_company: string | null;
    /**
     * Company Shipped At
     */
    company_shipped_at: string | null;
    /**
     * Company Tracking Number
     */
    company_tracking_number: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    /**
     * Courier Company
     */
    courier_company: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Customer Actions
     */
    customer_actions?: Array<string>;
    /**
     * Delivered At
     */
    delivered_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Items
     */
    items?: Array<OrderItemOut>;
    /**
     * Order Number
     */
    order_number: string;
    /**
     * Order Type
     */
    order_type: string;
    /**
     * Original Price
     */
    original_price: number;
    /**
     * Payment Group Id
     */
    payment_group_id: string | null;
    /**
     * Shipped At
     */
    shipped_at: string | null;
    /**
     * Shipping Address Id
     */
    shipping_address_id: string | null;
    /**
     * Shipping Cost
     */
    shipping_cost: number;
    /**
     * Status
     */
    status: string;
    /**
     * Total Discount
     */
    total_discount: number;
    /**
     * Total Price
     */
    total_price: number;
    /**
     * Tracking Number
     */
    tracking_number: string | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AdminQuoteStatusRequest
 */
export type AdminQuoteStatusRequest = {
    /**
     * Admin Memo
     */
    admin_memo?: string | null;
    /**
     * Memo
     */
    memo?: string | null;
    /**
     * New Status
     */
    new_status: '요청' | '견적발송' | '협의중' | '확정' | '종료';
    /**
     * Quote Conditions
     */
    quote_conditions?: string | null;
    /**
     * Quoted Amount
     */
    quoted_amount?: number | null;
};

/**
 * AdminQuoteStatusResponse
 */
export type AdminQuoteStatusResponse = {
    /**
     * New Status
     */
    new_status: string;
    /**
     * Previous Status
     */
    previous_status: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * AdminStatusUpdateRequest
 */
export type AdminStatusUpdateRequest = {
    /**
     * Is Rollback
     */
    is_rollback?: boolean;
    /**
     * Memo
     */
    memo?: string | null;
    /**
     * New Status
     */
    new_status: string;
};

/**
 * AdminStatusUpdateResponse
 */
export type AdminStatusUpdateResponse = {
    /**
     * New Status
     */
    new_status: string;
    /**
     * Previous Status
     */
    previous_status: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * AdminTokenManageRequest
 */
export type AdminTokenManageRequest = {
    /**
     * Amount
     */
    amount: number;
    /**
     * Description
     */
    description: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * AdminTokenManageResponse
 */
export type AdminTokenManageResponse = {
    /**
     * New Balance
     */
    new_balance: number;
    /**
     * Success
     */
    success: boolean;
};

/**
 * AdminTrackingUpdateRequest
 */
export type AdminTrackingUpdateRequest = {
    /**
     * Company Courier Company
     */
    company_courier_company?: string | null;
    /**
     * Company Tracking Number
     */
    company_tracking_number?: string | null;
    /**
     * Courier Company
     */
    courier_company?: string | null;
    /**
     * Tracking Number
     */
    tracking_number?: string | null;
};

/**
 * AdminUserOut
 */
export type AdminUserOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Phone Verified
     */
    phone_verified: boolean;
    /**
     * Role
     */
    role: string;
};

/**
 * AffectedResponse
 */
export type AffectedResponse = {
    /**
     * Affected Count
     */
    affected_count: number;
    /**
     * Success
     */
    success?: boolean;
};

/**
 * BatchResult
 */
export type BatchResult = {
    /**
     * Processed
     */
    processed: number;
};

/**
 * CartItemIn
 */
export type CartItemIn = {
    /**
     * Applied User Coupon Id
     */
    applied_user_coupon_id?: string | null;
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Item Type
     */
    item_type: 'product' | 'reform';
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Reform Data
     */
    reform_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Selected Option Id
     */
    selected_option_id?: string | null;
};

/**
 * CartItemOut
 */
export type CartItemOut = {
    applied_coupon: UserCouponOut | null;
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Item Type
     */
    item_type: string;
    product: ProductOut | null;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Reform Data
     */
    reform_data: {
        [key: string]: unknown;
    } | null;
    selected_option: ProductOptionOut | null;
};

/**
 * CartRemoveRequest
 */
export type CartRemoveRequest = {
    /**
     * Item Ids
     */
    item_ids: Array<string>;
};

/**
 * CartReplaceRequest
 */
export type CartReplaceRequest = {
    /**
     * Items
     */
    items: Array<CartItemIn>;
};

/**
 * ClaimCreateRequest
 */
export type ClaimCreateRequest = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Quantity
     */
    quantity?: number | null;
    /**
     * Reason
     */
    reason: 'change_mind' | 'defect' | 'delay' | 'wrong_item' | 'size_mismatch' | 'color_mismatch' | 'other';
    /**
     * Type
     */
    type: 'cancel' | 'return' | 'exchange';
};

/**
 * ClaimOut
 */
export type ClaimOut = {
    /**
     * Claim Number
     */
    claim_number: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Order Item Id
     */
    order_item_id: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Reason
     */
    reason: string;
    /**
     * Refund Data
     */
    refund_data: {
        [key: string]: unknown;
    } | null;
    /**
     * Resend Courier Company
     */
    resend_courier_company: string | null;
    /**
     * Resend Tracking Number
     */
    resend_tracking_number: string | null;
    /**
     * Return Courier Company
     */
    return_courier_company: string | null;
    /**
     * Return Tracking Number
     */
    return_tracking_number: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ConfirmedOrder
 */
export type ConfirmedOrder = {
    /**
     * Coupon Issued
     */
    coupon_issued?: boolean;
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Order Number
     */
    order_number: string;
    /**
     * Order Type
     */
    order_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Token Amount
     */
    token_amount?: number | null;
};

/**
 * CouponCreateRequest
 */
export type CouponCreateRequest = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Discount Type
     */
    discount_type: 'percentage' | 'fixed';
    /**
     * Discount Value
     */
    discount_value: number;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Expiry Date
     */
    expiry_date: string;
    /**
     * Max Discount Amount
     */
    max_discount_amount?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * CouponIssueRequest
 */
export type CouponIssueRequest = {
    /**
     * User Ids
     */
    user_ids: Array<string>;
};

/**
 * CouponOut
 */
export type CouponOut = {
    /**
     * Additional Info
     */
    additional_info: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Discount Type
     */
    discount_type: string;
    /**
     * Discount Value
     */
    discount_value: string;
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Expiry Date
     */
    expiry_date: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Max Discount Amount
     */
    max_discount_amount: string | null;
    /**
     * Name
     */
    name: string;
};

/**
 * CreatedOrder
 */
export type CreatedOrder = {
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Order Number
     */
    order_number: string;
    /**
     * Order Type
     */
    order_type: string;
};

/**
 * CustomAmountRequest
 */
export type CustomAmountRequest = {
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * CustomAmountResponse
 */
export type CustomAmountResponse = {
    /**
     * Fabric Cost
     */
    fabric_cost: number;
    /**
     * Sewing Cost
     */
    sewing_cost: number;
    /**
     * Total Cost
     */
    total_cost: number;
};

/**
 * CustomOrderCreateRequest
 */
export type CustomOrderCreateRequest = {
    /**
     * Additional Notes
     */
    additional_notes?: string;
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Reference Images
     */
    reference_images?: Array<ReferenceImageIn>;
    /**
     * Shipping Address Id
     */
    shipping_address_id: string;
    /**
     * User Coupon Id
     */
    user_coupon_id?: string | null;
};

/**
 * DesignSessionOut
 */
export type DesignSessionOut = {
    /**
     * Colorway
     */
    colorway: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Current Intent
     */
    current_intent: {
        [key: string]: unknown;
    } | null;
    /**
     * Finalize Used
     */
    finalize_used: number;
    /**
     * Id
     */
    id: string;
    /**
     * Recraft Used
     */
    recraft_used: number;
    /**
     * Registry Version
     */
    registry_version: string | null;
    /**
     * Seed
     */
    seed: number | null;
    /**
     * Status
     */
    status: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DesignSessionUpdateRequest
 */
export type DesignSessionUpdateRequest = {
    /**
     * Colorway
     */
    colorway?: string | null;
    /**
     * Current Intent
     */
    current_intent?: {
        [key: string]: unknown;
    } | null;
    /**
     * Seed
     */
    seed?: number | null;
};

/**
 * DesignTurnCreateRequest
 */
export type DesignTurnCreateRequest = {
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Role
     */
    role: string;
};

/**
 * DesignTurnOut
 */
export type DesignTurnOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Role
     */
    role: string;
    /**
     * Seq
     */
    seq: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageOut
 */
export type ImageOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Entity Id
     */
    entity_id: string;
    /**
     * Entity Type
     */
    entity_type: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Object Key
     */
    object_key: string;
};

/**
 * InquiryAnswerRequest
 */
export type InquiryAnswerRequest = {
    /**
     * Answer
     */
    answer: string;
};

/**
 * InquiryCreateRequest
 */
export type InquiryCreateRequest = {
    /**
     * Category
     */
    category?: '일반' | '상품' | '수선' | '주문제작';
    /**
     * Content
     */
    content: string;
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Title
     */
    title: string;
};

/**
 * InquiryOut
 */
export type InquiryOut = {
    /**
     * Answer
     */
    answer: string | null;
    /**
     * Answer Date
     */
    answer_date: string | null;
    /**
     * Category
     */
    category: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    product_id: number | null;
    /**
     * Status
     */
    status: string;
    /**
     * Title
     */
    title: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MeResponse
 */
export type MeResponse = {
    /**
     * Birth
     */
    birth: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Marketing Kakao Sms Consent
     */
    marketing_kakao_sms_consent: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Notification Consent
     */
    notification_consent: boolean;
    /**
     * Notification Enabled
     */
    notification_enabled: boolean;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Phone Verified
     */
    phone_verified: boolean;
    /**
     * Role
     */
    role: string;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * NotificationPreferencesRequest
 */
export type NotificationPreferencesRequest = {
    /**
     * Notification Consent
     */
    notification_consent?: boolean | null;
    /**
     * Notification Enabled
     */
    notification_enabled?: boolean | null;
};

/**
 * OrderCreateRequest
 */
export type OrderCreateRequest = {
    /**
     * Items
     */
    items: Array<OrderItemIn>;
    repair_shipping?: RepairShippingIn | null;
    /**
     * Shipping Address Id
     */
    shipping_address_id: string;
};

/**
 * OrderCreateResponse
 */
export type OrderCreateResponse = {
    /**
     * Orders
     */
    orders: Array<CreatedOrder>;
    /**
     * Payment Group Id
     */
    payment_group_id: string;
    /**
     * Total Amount
     */
    total_amount: number;
};

/**
 * OrderItemIn
 */
export type OrderItemIn = {
    /**
     * Applied User Coupon Id
     */
    applied_user_coupon_id?: string | null;
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Item Type
     */
    item_type: 'product' | 'reform';
    /**
     * Product Id
     */
    product_id?: number | null;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Reform Data
     */
    reform_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Selected Option Id
     */
    selected_option_id?: string | null;
};

/**
 * OrderItemOut
 */
export type OrderItemOut = {
    /**
     * Applied User Coupon Id
     */
    applied_user_coupon_id: string | null;
    /**
     * Discount Amount
     */
    discount_amount: number;
    /**
     * Id
     */
    id: string;
    /**
     * Item Data
     */
    item_data: {
        [key: string]: unknown;
    } | null;
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Item Type
     */
    item_type: string;
    /**
     * Line Discount Amount
     */
    line_discount_amount: number;
    /**
     * Product Id
     */
    product_id: number | null;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Selected Option Id
     */
    selected_option_id: string | null;
    /**
     * Unit Price
     */
    unit_price: number;
};

/**
 * OrderOut
 */
export type OrderOut = {
    /**
     * Company Courier Company
     */
    company_courier_company: string | null;
    /**
     * Company Shipped At
     */
    company_shipped_at: string | null;
    /**
     * Company Tracking Number
     */
    company_tracking_number: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    /**
     * Courier Company
     */
    courier_company: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Customer Actions
     */
    customer_actions?: Array<string>;
    /**
     * Delivered At
     */
    delivered_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Items
     */
    items?: Array<OrderItemOut>;
    /**
     * Order Number
     */
    order_number: string;
    /**
     * Order Type
     */
    order_type: string;
    /**
     * Original Price
     */
    original_price: number;
    /**
     * Payment Group Id
     */
    payment_group_id: string | null;
    /**
     * Shipped At
     */
    shipped_at: string | null;
    /**
     * Shipping Address Id
     */
    shipping_address_id: string | null;
    /**
     * Shipping Cost
     */
    shipping_cost: number;
    /**
     * Status
     */
    status: string;
    /**
     * Total Discount
     */
    total_discount: number;
    /**
     * Total Price
     */
    total_price: number;
    /**
     * Tracking Number
     */
    tracking_number: string | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PaymentConfirmRequest
 */
export type PaymentConfirmRequest = {
    /**
     * Amount
     */
    amount: number;
    /**
     * Payment Group Id
     */
    payment_group_id: string;
    /**
     * Payment Key
     */
    payment_key: string;
};

/**
 * PaymentConfirmResponse
 */
export type PaymentConfirmResponse = {
    /**
     * Orders
     */
    orders: Array<ConfirmedOrder>;
    /**
     * Success
     */
    success?: boolean;
    /**
     * Token Amount
     */
    token_amount?: number | null;
};

/**
 * PhoneSendRequest
 */
export type PhoneSendRequest = {
    /**
     * Phone
     */
    phone: string;
};

/**
 * PhoneVerifyRequest
 */
export type PhoneVerifyRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Phone
     */
    phone: string;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Category
     */
    category: '3fold' | 'sfolderato' | 'knit' | 'bowtie';
    /**
     * Code
     */
    code?: string | null;
    /**
     * Color
     */
    color: 'black' | 'navy' | 'gray' | 'wine' | 'blue' | 'brown' | 'beige' | 'silver';
    /**
     * Detail Images
     */
    detail_images?: Array<string> | null;
    /**
     * Image
     */
    image: string;
    /**
     * Info
     */
    info: string;
    /**
     * Material
     */
    material: 'silk' | 'cotton' | 'polyester' | 'wool';
    /**
     * Name
     */
    name: string;
    /**
     * Option Label
     */
    option_label?: string | null;
    /**
     * Pattern
     */
    pattern: 'solid' | 'stripe' | 'dot' | 'check' | 'paisley';
    /**
     * Price
     */
    price: number;
    /**
     * Stock
     */
    stock?: number | null;
};

/**
 * ProductOptionIn
 */
export type ProductOptionIn = {
    /**
     * Additional Price
     */
    additional_price?: number;
    /**
     * Name
     */
    name: string;
    /**
     * Stock
     */
    stock?: number | null;
};

/**
 * ProductOptionOut
 */
export type ProductOptionOut = {
    /**
     * Additional Price
     */
    additional_price: number;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Stock
     */
    stock: number | null;
};

/**
 * ProductOut
 */
export type ProductOut = {
    /**
     * Category
     */
    category: string;
    /**
     * Code
     */
    code: string | null;
    /**
     * Color
     */
    color: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Detail Images
     */
    detail_images: Array<string> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Image
     */
    image: string;
    /**
     * Info
     */
    info: string;
    /**
     * Is Liked
     */
    is_liked?: boolean;
    /**
     * Likes
     */
    likes?: number;
    /**
     * Material
     */
    material: string;
    /**
     * Name
     */
    name: string;
    /**
     * Option Label
     */
    option_label: string | null;
    /**
     * Options
     */
    options?: Array<ProductOptionOut>;
    /**
     * Pattern
     */
    pattern: string;
    /**
     * Price
     */
    price: number;
    /**
     * Stock
     */
    stock: number | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProductUpdate
 */
export type ProductUpdate = {
    /**
     * Category
     */
    category?: '3fold' | 'sfolderato' | 'knit' | 'bowtie' | null;
    /**
     * Color
     */
    color?: 'black' | 'navy' | 'gray' | 'wine' | 'blue' | 'brown' | 'beige' | 'silver' | null;
    /**
     * Detail Images
     */
    detail_images?: Array<string> | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Info
     */
    info?: string | null;
    /**
     * Material
     */
    material?: 'silk' | 'cotton' | 'polyester' | 'wool' | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Option Label
     */
    option_label?: string | null;
    /**
     * Pattern
     */
    pattern?: 'solid' | 'stripe' | 'dot' | 'check' | 'paisley' | null;
    /**
     * Price
     */
    price?: number | null;
    /**
     * Stock
     */
    stock?: number | null;
};

/**
 * ProfileUpdateRequest
 *
 * 본인 수정 허용 필드만 — phone_verified/notification_*role은 전용 경로.
 */
export type ProfileUpdateRequest = {
    /**
     * Birth
     */
    birth?: string | null;
    /**
     * Marketing Kakao Sms Consent
     */
    marketing_kakao_sms_consent?: boolean | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
};

/**
 * QuoteCreateRequest
 */
export type QuoteCreateRequest = {
    /**
     * Additional Notes
     */
    additional_notes?: string;
    /**
     * Business Name
     */
    business_name?: string;
    /**
     * Contact Method
     */
    contact_method: 'email' | 'phone';
    /**
     * Contact Name
     */
    contact_name: string;
    /**
     * Contact Value
     */
    contact_value: string;
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Reference Images
     */
    reference_images?: Array<ReferenceImageIn>;
    /**
     * Shipping Address Id
     */
    shipping_address_id: string;
};

/**
 * QuoteOut
 */
export type QuoteOut = {
    /**
     * Additional Notes
     */
    additional_notes: string;
    /**
     * Admin Memo
     */
    admin_memo: string | null;
    /**
     * Business Name
     */
    business_name: string;
    /**
     * Contact Method
     */
    contact_method: string;
    /**
     * Contact Name
     */
    contact_name: string;
    /**
     * Contact Value
     */
    contact_value: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Quote Conditions
     */
    quote_conditions: string | null;
    /**
     * Quote Number
     */
    quote_number: string;
    /**
     * Quoted Amount
     */
    quoted_amount: number | null;
    /**
     * Reference Images
     */
    reference_images: Array<unknown>;
    /**
     * Shipping Address Id
     */
    shipping_address_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ReferenceImageIn
 */
export type ReferenceImageIn = {
    /**
     * Object Key
     */
    object_key: string;
};

/**
 * RefundableTokenOrder
 */
export type RefundableTokenOrder = {
    /**
     * Is Refundable
     */
    is_refundable: boolean;
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Order Number
     */
    order_number: string;
    /**
     * Paid Tokens Granted
     */
    paid_tokens_granted: number;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Token Expires At
     */
    token_expires_at: string | null;
    /**
     * Total Price
     */
    total_price: number;
};

/**
 * RepairNoTrackingRequest
 */
export type RepairNoTrackingRequest = {
    /**
     * Memo
     */
    memo?: string | null;
    /**
     * Photos
     */
    photos?: Array<RepairPhotoIn>;
    /**
     * Reason
     */
    reason: 'quick' | 'overseas' | 'lost';
};

/**
 * RepairPhotoIn
 */
export type RepairPhotoIn = {
    /**
     * Object Key
     */
    object_key: string;
};

/**
 * RepairPickupIn
 */
export type RepairPickupIn = {
    /**
     * Address
     */
    address: string;
    /**
     * Detail Address
     */
    detail_address?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Recipient Name
     */
    recipient_name: string;
    /**
     * Recipient Phone
     */
    recipient_phone: string;
};

/**
 * RepairShippingIn
 */
export type RepairShippingIn = {
    /**
     * Method
     */
    method: 'direct' | 'pickup';
    pickup?: RepairPickupIn | null;
};

/**
 * RepairTrackingRequest
 */
export type RepairTrackingRequest = {
    /**
     * Courier Company
     */
    courier_company: string;
    /**
     * Photos
     */
    photos?: Array<RepairPhotoIn>;
    /**
     * Tracking Number
     */
    tracking_number: string;
};

/**
 * RevokeByIdsRequest
 */
export type RevokeByIdsRequest = {
    /**
     * User Coupon Ids
     */
    user_coupon_ids: Array<string>;
};

/**
 * SampleOrderCreateRequest
 */
export type SampleOrderCreateRequest = {
    /**
     * Additional Notes
     */
    additional_notes?: string;
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
    /**
     * Reference Images
     */
    reference_images?: Array<ReferenceImageIn>;
    /**
     * Sample Type
     */
    sample_type: 'fabric' | 'sewing' | 'fabric_and_sewing';
    /**
     * Shipping Address Id
     */
    shipping_address_id: string;
    /**
     * User Coupon Id
     */
    user_coupon_id?: string | null;
};

/**
 * ShippingAddressIn
 */
export type ShippingAddressIn = {
    /**
     * Address
     */
    address: string;
    /**
     * Address Detail
     */
    address_detail?: string | null;
    /**
     * Delivery Memo
     */
    delivery_memo?: string | null;
    /**
     * Delivery Request
     */
    delivery_request?: string | null;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * Postal Code
     */
    postal_code: string;
    /**
     * Recipient Name
     */
    recipient_name: string;
    /**
     * Recipient Phone
     */
    recipient_phone: string;
};

/**
 * ShippingAddressOut
 */
export type ShippingAddressOut = {
    /**
     * Address
     */
    address: string;
    /**
     * Address Detail
     */
    address_detail: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Delivery Memo
     */
    delivery_memo: string | null;
    /**
     * Delivery Request
     */
    delivery_request: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Postal Code
     */
    postal_code: string;
    /**
     * Recipient Name
     */
    recipient_name: string;
    /**
     * Recipient Phone
     */
    recipient_phone: string;
};

/**
 * SingleOrderCreateResponse
 */
export type SingleOrderCreateResponse = {
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Order Number
     */
    order_number: string;
    /**
     * Payment Group Id
     */
    payment_group_id: string;
    /**
     * Total Amount
     */
    total_amount: number;
};

/**
 * StatsResponse
 */
export type StatsResponse = {
    /**
     * Order Count
     */
    order_count: number;
    /**
     * Revenue
     */
    revenue: number;
};

/**
 * TokenBalance
 */
export type TokenBalance = {
    /**
     * Bonus
     */
    bonus: number;
    /**
     * Paid
     */
    paid: number;
    /**
     * Total
     */
    total: number;
};

/**
 * TokenOrderCreateRequest
 */
export type TokenOrderCreateRequest = {
    /**
     * Plan Key
     */
    plan_key: 'starter' | 'popular' | 'pro';
};

/**
 * TokenOrderCreateResponse
 */
export type TokenOrderCreateResponse = {
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Order Number
     */
    order_number: string;
    /**
     * Payment Group Id
     */
    payment_group_id: string;
    /**
     * Price
     */
    price: number;
    /**
     * Token Amount
     */
    token_amount: number;
};

/**
 * TokenPlan
 */
export type TokenPlan = {
    /**
     * Plan Key
     */
    plan_key: string;
    /**
     * Price
     */
    price: number;
    /**
     * Token Amount
     */
    token_amount: number;
};

/**
 * TokenRefundRequestIn
 */
export type TokenRefundRequestIn = {
    /**
     * Order Id
     */
    order_id: string;
};

/**
 * TokenRefundRequestOut
 */
export type TokenRefundRequestOut = {
    /**
     * Bonus Token Amount
     */
    bonus_token_amount: number;
    /**
     * Claim Id
     */
    claim_id: string;
    /**
     * Claim Number
     */
    claim_number: string;
    /**
     * Paid Token Amount
     */
    paid_token_amount: number;
    /**
     * Refund Amount
     */
    refund_amount: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UploadRegisterRequest
 */
export type UploadRegisterRequest = {
    /**
     * Object Key
     */
    object_key: string;
};

/**
 * UploadUrlRequest
 */
export type UploadUrlRequest = {
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Kind
     */
    kind: 'reform_upload' | 'repair_shipping_upload' | 'custom_order' | 'sample_order' | 'quote_request';
};

/**
 * UploadUrlResponse
 */
export type UploadUrlResponse = {
    /**
     * Object Key
     */
    object_key: string;
    /**
     * Upload Url
     */
    upload_url: string;
};

/**
 * UserCouponOut
 */
export type UserCouponOut = {
    coupon?: CouponOut | null;
    /**
     * Coupon Id
     */
    coupon_id: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Issued At
     */
    issued_at: string;
    /**
     * Status
     */
    status: string;
    /**
     * Used At
     */
    used_at: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AdminListClaimsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/claims';
};

export type AdminListClaimsResponses = {
    /**
     * Response Admin List Claims
     *
     * Successful Response
     */
    200: Array<ClaimOut>;
};

export type AdminListClaimsResponse = AdminListClaimsResponses[keyof AdminListClaimsResponses];

export type AdminUpdateClaimStatusData = {
    body: AdminClaimStatusRequest;
    path: {
        /**
         * Claim Id
         */
        claim_id: string;
    };
    query?: never;
    url: '/admin/claims/{claim_id}/status';
};

export type AdminUpdateClaimStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateClaimStatusError = AdminUpdateClaimStatusErrors[keyof AdminUpdateClaimStatusErrors];

export type AdminUpdateClaimStatusResponses = {
    /**
     * Successful Response
     */
    200: AdminClaimStatusResponse;
};

export type AdminUpdateClaimStatusResponse = AdminUpdateClaimStatusResponses[keyof AdminUpdateClaimStatusResponses];

export type ListCouponsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/coupons';
};

export type ListCouponsResponses = {
    /**
     * Response List Coupons
     *
     * Successful Response
     */
    200: Array<CouponOut>;
};

export type ListCouponsResponse = ListCouponsResponses[keyof ListCouponsResponses];

export type CreateCouponData = {
    body: CouponCreateRequest;
    path?: never;
    query?: never;
    url: '/admin/coupons';
};

export type CreateCouponErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCouponError = CreateCouponErrors[keyof CreateCouponErrors];

export type CreateCouponResponses = {
    /**
     * Successful Response
     */
    201: CouponOut;
};

export type CreateCouponResponse = CreateCouponResponses[keyof CreateCouponResponses];

export type RevokeCouponsByIdsData = {
    body: RevokeByIdsRequest;
    path?: never;
    query?: never;
    url: '/admin/coupons/revoke';
};

export type RevokeCouponsByIdsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeCouponsByIdsError = RevokeCouponsByIdsErrors[keyof RevokeCouponsByIdsErrors];

export type RevokeCouponsByIdsResponses = {
    /**
     * Successful Response
     */
    200: AffectedResponse;
};

export type RevokeCouponsByIdsResponse = RevokeCouponsByIdsResponses[keyof RevokeCouponsByIdsResponses];

export type BulkIssueCouponsData = {
    body: CouponIssueRequest;
    path: {
        /**
         * Coupon Id
         */
        coupon_id: string;
    };
    query?: never;
    url: '/admin/coupons/{coupon_id}/issue';
};

export type BulkIssueCouponsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkIssueCouponsError = BulkIssueCouponsErrors[keyof BulkIssueCouponsErrors];

export type BulkIssueCouponsResponses = {
    /**
     * Successful Response
     */
    200: AffectedResponse;
};

export type BulkIssueCouponsResponse = BulkIssueCouponsResponses[keyof BulkIssueCouponsResponses];

export type RevokeCouponsByUsersData = {
    body: CouponIssueRequest;
    path: {
        /**
         * Coupon Id
         */
        coupon_id: string;
    };
    query?: never;
    url: '/admin/coupons/{coupon_id}/revoke-users';
};

export type RevokeCouponsByUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeCouponsByUsersError = RevokeCouponsByUsersErrors[keyof RevokeCouponsByUsersErrors];

export type RevokeCouponsByUsersResponses = {
    /**
     * Successful Response
     */
    200: AffectedResponse;
};

export type RevokeCouponsByUsersResponse = RevokeCouponsByUsersResponses[keyof RevokeCouponsByUsersResponses];

export type AdminListInquiriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/inquiries';
};

export type AdminListInquiriesResponses = {
    /**
     * Response Admin List Inquiries
     *
     * Successful Response
     */
    200: Array<InquiryOut>;
};

export type AdminListInquiriesResponse = AdminListInquiriesResponses[keyof AdminListInquiriesResponses];

export type AnswerInquiryData = {
    body: InquiryAnswerRequest;
    path: {
        /**
         * Inquiry Id
         */
        inquiry_id: string;
    };
    query?: never;
    url: '/admin/inquiries/{inquiry_id}/answer';
};

export type AnswerInquiryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerInquiryError = AnswerInquiryErrors[keyof AnswerInquiryErrors];

export type AnswerInquiryResponses = {
    /**
     * Successful Response
     */
    200: InquiryOut;
};

export type AnswerInquiryResponse = AnswerInquiryResponses[keyof AnswerInquiryResponses];

export type ListAllOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Order Type
         */
        order_type?: 'all' | 'sale' | 'custom' | 'repair' | 'token' | 'sample';
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/admin/orders';
};

export type ListAllOrdersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAllOrdersError = ListAllOrdersErrors[keyof ListAllOrdersErrors];

export type ListAllOrdersResponses = {
    /**
     * Response List All Orders
     *
     * Successful Response
     */
    200: Array<AdminOrderOut>;
};

export type ListAllOrdersResponse = ListAllOrdersResponses[keyof ListAllOrdersResponses];

export type AdminUpdateOrderStatusData = {
    body: AdminStatusUpdateRequest;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/admin/orders/{order_id}/status';
};

export type AdminUpdateOrderStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateOrderStatusError = AdminUpdateOrderStatusErrors[keyof AdminUpdateOrderStatusErrors];

export type AdminUpdateOrderStatusResponses = {
    /**
     * Successful Response
     */
    200: AdminStatusUpdateResponse;
};

export type AdminUpdateOrderStatusResponse = AdminUpdateOrderStatusResponses[keyof AdminUpdateOrderStatusResponses];

export type AdminUpdateOrderTrackingData = {
    body: AdminTrackingUpdateRequest;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/admin/orders/{order_id}/tracking';
};

export type AdminUpdateOrderTrackingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateOrderTrackingError = AdminUpdateOrderTrackingErrors[keyof AdminUpdateOrderTrackingErrors];

export type AdminUpdateOrderTrackingResponses = {
    /**
     * Successful Response
     */
    200: OrderOut;
};

export type AdminUpdateOrderTrackingResponse = AdminUpdateOrderTrackingResponses[keyof AdminUpdateOrderTrackingResponses];

export type CreateProductData = {
    body: ProductCreate;
    path?: never;
    query?: never;
    url: '/admin/products';
};

export type CreateProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
    /**
     * Successful Response
     */
    201: ProductOut;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type UpdateProductData = {
    body: ProductUpdate;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/admin/products/{product_id}';
};

export type UpdateProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductOut;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type ReplaceProductOptionsData = {
    /**
     * Body
     */
    body: Array<ProductOptionIn>;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/admin/products/{product_id}/options';
};

export type ReplaceProductOptionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceProductOptionsError = ReplaceProductOptionsErrors[keyof ReplaceProductOptionsErrors];

export type ReplaceProductOptionsResponses = {
    /**
     * Response Replace Product Options
     *
     * Successful Response
     */
    200: Array<ProductOptionOut>;
};

export type ReplaceProductOptionsResponse = ReplaceProductOptionsResponses[keyof ReplaceProductOptionsResponses];

export type AdminListQuotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/quotes';
};

export type AdminListQuotesResponses = {
    /**
     * Response Admin List Quotes
     *
     * Successful Response
     */
    200: Array<QuoteOut>;
};

export type AdminListQuotesResponse = AdminListQuotesResponses[keyof AdminListQuotesResponses];

export type AdminUpdateQuoteStatusData = {
    body: AdminQuoteStatusRequest;
    path: {
        /**
         * Quote Id
         */
        quote_id: string;
    };
    query?: never;
    url: '/admin/quotes/{quote_id}/status';
};

export type AdminUpdateQuoteStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateQuoteStatusError = AdminUpdateQuoteStatusErrors[keyof AdminUpdateQuoteStatusErrors];

export type AdminUpdateQuoteStatusResponses = {
    /**
     * Successful Response
     */
    200: AdminQuoteStatusResponse;
};

export type AdminUpdateQuoteStatusResponse = AdminUpdateQuoteStatusResponses[keyof AdminUpdateQuoteStatusResponses];

export type PeriodStatsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Start Date
         */
        start_date: string;
        /**
         * End Date
         */
        end_date: string;
        /**
         * Order Type
         */
        order_type?: 'all' | 'sale' | 'custom' | 'repair' | 'token' | 'sample';
    };
    url: '/admin/stats/period';
};

export type PeriodStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PeriodStatsError = PeriodStatsErrors[keyof PeriodStatsErrors];

export type PeriodStatsResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type PeriodStatsResponse = PeriodStatsResponses[keyof PeriodStatsResponses];

export type TodayStatsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Stat Date
         */
        stat_date: string;
        /**
         * Order Type
         */
        order_type?: 'all' | 'sale' | 'custom' | 'repair' | 'token' | 'sample';
    };
    url: '/admin/stats/today';
};

export type TodayStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TodayStatsError = TodayStatsErrors[keyof TodayStatsErrors];

export type TodayStatsResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type TodayStatsResponse = TodayStatsResponses[keyof TodayStatsResponses];

export type AdminApproveTokenRefundData = {
    body?: never;
    path: {
        /**
         * Claim Id
         */
        claim_id: string;
    };
    query?: never;
    url: '/admin/token-refunds/{claim_id}/approve';
};

export type AdminApproveTokenRefundErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminApproveTokenRefundError = AdminApproveTokenRefundErrors[keyof AdminApproveTokenRefundErrors];

export type AdminApproveTokenRefundResponses = {
    /**
     * Response Admin Approve Token Refund
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminApproveTokenRefundResponse = AdminApproveTokenRefundResponses[keyof AdminApproveTokenRefundResponses];

export type AdminManageTokensData = {
    body: AdminTokenManageRequest;
    path?: never;
    query?: never;
    url: '/admin/tokens/manage';
};

export type AdminManageTokensErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminManageTokensError = AdminManageTokensErrors[keyof AdminManageTokensErrors];

export type AdminManageTokensResponses = {
    /**
     * Successful Response
     */
    200: AdminTokenManageResponse;
};

export type AdminManageTokensResponse = AdminManageTokensResponses[keyof AdminManageTokensResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type ListUsersResponses = {
    /**
     * Response List Users
     *
     * Successful Response
     */
    200: Array<AdminUserOut>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type SendPhoneVerificationData = {
    body: PhoneSendRequest;
    path?: never;
    query?: never;
    url: '/auth/phone/send';
};

export type SendPhoneVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendPhoneVerificationError = SendPhoneVerificationErrors[keyof SendPhoneVerificationErrors];

export type SendPhoneVerificationResponses = {
    /**
     * Successful Response
     */
    202: MessageResponse;
};

export type SendPhoneVerificationResponse = SendPhoneVerificationResponses[keyof SendPhoneVerificationResponses];

export type VerifyPhoneData = {
    body: PhoneVerifyRequest;
    path?: never;
    query?: never;
    url: '/auth/phone/verify';
};

export type VerifyPhoneErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyPhoneError = VerifyPhoneErrors[keyof VerifyPhoneErrors];

export type VerifyPhoneResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type VerifyPhoneResponse = VerifyPhoneResponses[keyof VerifyPhoneResponses];

export type RefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokensResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RefreshTokensResponse = RefreshTokensResponses[keyof RefreshTokensResponses];

export type AutoConfirmOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/batch/auto-confirm-orders';
};

export type AutoConfirmOrdersResponses = {
    /**
     * Successful Response
     */
    200: BatchResult;
};

export type AutoConfirmOrdersResponse = AutoConfirmOrdersResponses[keyof AutoConfirmOrdersResponses];

export type CancelStaleOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/batch/cancel-stale-orders';
};

export type CancelStaleOrdersResponses = {
    /**
     * Successful Response
     */
    200: BatchResult;
};

export type CancelStaleOrdersResponse = CancelStaleOrdersResponses[keyof CancelStaleOrdersResponses];

export type CleanupImagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/batch/cleanup-images';
};

export type CleanupImagesResponses = {
    /**
     * Successful Response
     */
    200: BatchResult;
};

export type CleanupImagesResponse = CleanupImagesResponses[keyof CleanupImagesResponses];

export type GetCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart';
};

export type GetCartResponses = {
    /**
     * Response Get Cart
     *
     * Successful Response
     */
    200: Array<CartItemOut>;
};

export type GetCartResponse = GetCartResponses[keyof GetCartResponses];

export type ReplaceCartData = {
    body: CartReplaceRequest;
    path?: never;
    query?: never;
    url: '/cart';
};

export type ReplaceCartErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceCartError = ReplaceCartErrors[keyof ReplaceCartErrors];

export type ReplaceCartResponses = {
    /**
     * Response Replace Cart
     *
     * Successful Response
     */
    200: Array<CartItemOut>;
};

export type ReplaceCartResponse = ReplaceCartResponses[keyof ReplaceCartResponses];

export type RemoveCartItemsData = {
    body: CartRemoveRequest;
    path?: never;
    query?: never;
    url: '/cart/remove';
};

export type RemoveCartItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveCartItemsError = RemoveCartItemsErrors[keyof RemoveCartItemsErrors];

export type RemoveCartItemsResponses = {
    /**
     * Response Remove Cart Items
     *
     * Successful Response
     */
    200: Array<CartItemOut>;
};

export type RemoveCartItemsResponse = RemoveCartItemsResponses[keyof RemoveCartItemsResponses];

export type ListMyClaimsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/claims';
};

export type ListMyClaimsResponses = {
    /**
     * Response List My Claims
     *
     * Successful Response
     */
    200: Array<ClaimOut>;
};

export type ListMyClaimsResponse = ListMyClaimsResponses[keyof ListMyClaimsResponses];

export type CreateClaimData = {
    body: ClaimCreateRequest;
    path?: never;
    query?: never;
    url: '/claims';
};

export type CreateClaimErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClaimError = CreateClaimErrors[keyof CreateClaimErrors];

export type CreateClaimResponses = {
    /**
     * Successful Response
     */
    201: ClaimOut;
};

export type CreateClaimResponse = CreateClaimResponses[keyof CreateClaimResponses];

export type CancelClaimData = {
    body?: never;
    path: {
        /**
         * Claim Id
         */
        claim_id: string;
    };
    query?: never;
    url: '/claims/{claim_id}';
};

export type CancelClaimErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelClaimError = CancelClaimErrors[keyof CancelClaimErrors];

export type CancelClaimResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CancelClaimResponse = CancelClaimResponses[keyof CancelClaimResponses];

export type ListMyCouponsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Active Only
         */
        active_only?: boolean;
    };
    url: '/coupons/mine';
};

export type ListMyCouponsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMyCouponsError = ListMyCouponsErrors[keyof ListMyCouponsErrors];

export type ListMyCouponsResponses = {
    /**
     * Response List My Coupons
     *
     * Successful Response
     */
    200: Array<UserCouponOut>;
};

export type ListMyCouponsResponse = ListMyCouponsResponses[keyof ListMyCouponsResponses];

export type ListDesignSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/design/sessions';
};

export type ListDesignSessionsResponses = {
    /**
     * Response List Design Sessions
     *
     * Successful Response
     */
    200: Array<DesignSessionOut>;
};

export type ListDesignSessionsResponse = ListDesignSessionsResponses[keyof ListDesignSessionsResponses];

export type CreateDesignSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/design/sessions';
};

export type CreateDesignSessionResponses = {
    /**
     * Successful Response
     */
    201: DesignSessionOut;
};

export type CreateDesignSessionResponse = CreateDesignSessionResponses[keyof CreateDesignSessionResponses];

export type GetDesignSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/design/sessions/{session_id}';
};

export type GetDesignSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDesignSessionError = GetDesignSessionErrors[keyof GetDesignSessionErrors];

export type GetDesignSessionResponses = {
    /**
     * Successful Response
     */
    200: DesignSessionOut;
};

export type GetDesignSessionResponse = GetDesignSessionResponses[keyof GetDesignSessionResponses];

export type UpdateDesignSessionData = {
    body: DesignSessionUpdateRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/design/sessions/{session_id}';
};

export type UpdateDesignSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDesignSessionError = UpdateDesignSessionErrors[keyof UpdateDesignSessionErrors];

export type UpdateDesignSessionResponses = {
    /**
     * Successful Response
     */
    200: DesignSessionOut;
};

export type UpdateDesignSessionResponse = UpdateDesignSessionResponses[keyof UpdateDesignSessionResponses];

export type ListDesignTurnsData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/design/sessions/{session_id}/turns';
};

export type ListDesignTurnsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDesignTurnsError = ListDesignTurnsErrors[keyof ListDesignTurnsErrors];

export type ListDesignTurnsResponses = {
    /**
     * Response List Design Turns
     *
     * Successful Response
     */
    200: Array<DesignTurnOut>;
};

export type ListDesignTurnsResponse = ListDesignTurnsResponses[keyof ListDesignTurnsResponses];

export type AppendDesignTurnData = {
    body: DesignTurnCreateRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/design/sessions/{session_id}/turns';
};

export type AppendDesignTurnErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppendDesignTurnError = AppendDesignTurnErrors[keyof AppendDesignTurnErrors];

export type AppendDesignTurnResponses = {
    /**
     * Successful Response
     */
    201: DesignTurnOut;
};

export type AppendDesignTurnResponse = AppendDesignTurnResponses[keyof AppendDesignTurnResponses];

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    /**
     * Response Healthz
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type RegisterReformUploadData = {
    body: UploadRegisterRequest;
    path?: never;
    query?: never;
    url: '/images/reform-uploads';
};

export type RegisterReformUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterReformUploadError = RegisterReformUploadErrors[keyof RegisterReformUploadErrors];

export type RegisterReformUploadResponses = {
    /**
     * Successful Response
     */
    201: ImageOut;
};

export type RegisterReformUploadResponse = RegisterReformUploadResponses[keyof RegisterReformUploadResponses];

export type RegisterRepairShippingUploadData = {
    body: UploadRegisterRequest;
    path?: never;
    query?: never;
    url: '/images/repair-shipping-uploads';
};

export type RegisterRepairShippingUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRepairShippingUploadError = RegisterRepairShippingUploadErrors[keyof RegisterRepairShippingUploadErrors];

export type RegisterRepairShippingUploadResponses = {
    /**
     * Successful Response
     */
    201: ImageOut;
};

export type RegisterRepairShippingUploadResponse = RegisterRepairShippingUploadResponses[keyof RegisterRepairShippingUploadResponses];

export type CreateUploadUrlData = {
    body: UploadUrlRequest;
    path?: never;
    query?: never;
    url: '/images/upload-url';
};

export type CreateUploadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUploadUrlError = CreateUploadUrlErrors[keyof CreateUploadUrlErrors];

export type CreateUploadUrlResponses = {
    /**
     * Successful Response
     */
    200: UploadUrlResponse;
};

export type CreateUploadUrlResponse = CreateUploadUrlResponses[keyof CreateUploadUrlResponses];

export type ListMyInquiriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inquiries';
};

export type ListMyInquiriesResponses = {
    /**
     * Response List My Inquiries
     *
     * Successful Response
     */
    200: Array<InquiryOut>;
};

export type ListMyInquiriesResponse = ListMyInquiriesResponses[keyof ListMyInquiriesResponses];

export type CreateInquiryData = {
    body: InquiryCreateRequest;
    path?: never;
    query?: never;
    url: '/inquiries';
};

export type CreateInquiryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInquiryError = CreateInquiryErrors[keyof CreateInquiryErrors];

export type CreateInquiryResponses = {
    /**
     * Successful Response
     */
    201: InquiryOut;
};

export type CreateInquiryResponse = CreateInquiryResponses[keyof CreateInquiryResponses];

export type GetInquiryData = {
    body?: never;
    path: {
        /**
         * Inquiry Id
         */
        inquiry_id: string;
    };
    query?: never;
    url: '/inquiries/{inquiry_id}';
};

export type GetInquiryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInquiryError = GetInquiryErrors[keyof GetInquiryErrors];

export type GetInquiryResponses = {
    /**
     * Successful Response
     */
    200: InquiryOut;
};

export type GetInquiryResponse = GetInquiryResponses[keyof GetInquiryResponses];

export type ListMyOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Order Type
         */
        order_type?: 'sale' | 'custom' | 'repair' | 'token' | 'sample' | null;
    };
    url: '/orders';
};

export type ListMyOrdersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMyOrdersError = ListMyOrdersErrors[keyof ListMyOrdersErrors];

export type ListMyOrdersResponses = {
    /**
     * Response List My Orders
     *
     * Successful Response
     */
    200: Array<OrderOut>;
};

export type ListMyOrdersResponse = ListMyOrdersResponses[keyof ListMyOrdersResponses];

export type CreateOrderData = {
    body: OrderCreateRequest;
    path?: never;
    query?: never;
    url: '/orders';
};

export type CreateOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export type CreateOrderResponses = {
    /**
     * Successful Response
     */
    201: OrderCreateResponse;
};

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];

export type CreateCustomOrderData = {
    body: CustomOrderCreateRequest;
    path?: never;
    query?: never;
    url: '/orders/custom';
};

export type CreateCustomOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCustomOrderError = CreateCustomOrderErrors[keyof CreateCustomOrderErrors];

export type CreateCustomOrderResponses = {
    /**
     * Successful Response
     */
    201: SingleOrderCreateResponse;
};

export type CreateCustomOrderResponse = CreateCustomOrderResponses[keyof CreateCustomOrderResponses];

export type CalculateCustomOrderData = {
    body: CustomAmountRequest;
    path?: never;
    query?: never;
    url: '/orders/custom/calculate';
};

export type CalculateCustomOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CalculateCustomOrderError = CalculateCustomOrderErrors[keyof CalculateCustomOrderErrors];

export type CalculateCustomOrderResponses = {
    /**
     * Successful Response
     */
    200: CustomAmountResponse;
};

export type CalculateCustomOrderResponse = CalculateCustomOrderResponses[keyof CalculateCustomOrderResponses];

export type CreateSampleOrderData = {
    body: SampleOrderCreateRequest;
    path?: never;
    query?: never;
    url: '/orders/sample';
};

export type CreateSampleOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSampleOrderError = CreateSampleOrderErrors[keyof CreateSampleOrderErrors];

export type CreateSampleOrderResponses = {
    /**
     * Successful Response
     */
    201: SingleOrderCreateResponse;
};

export type CreateSampleOrderResponse = CreateSampleOrderResponses[keyof CreateSampleOrderResponses];

export type GetOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/orders/{order_id}';
};

export type GetOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrderError = GetOrderErrors[keyof GetOrderErrors];

export type GetOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderOut;
};

export type GetOrderResponse = GetOrderResponses[keyof GetOrderResponses];

export type ConfirmPurchaseData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/orders/{order_id}/confirm-purchase';
};

export type ConfirmPurchaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmPurchaseError = ConfirmPurchaseErrors[keyof ConfirmPurchaseErrors];

export type ConfirmPurchaseResponses = {
    /**
     * Successful Response
     */
    200: OrderOut;
};

export type ConfirmPurchaseResponse = ConfirmPurchaseResponses[keyof ConfirmPurchaseResponses];

export type SubmitRepairNoTrackingData = {
    body: RepairNoTrackingRequest;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/orders/{order_id}/repair-no-tracking';
};

export type SubmitRepairNoTrackingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitRepairNoTrackingError = SubmitRepairNoTrackingErrors[keyof SubmitRepairNoTrackingErrors];

export type SubmitRepairNoTrackingResponses = {
    /**
     * Successful Response
     */
    200: OrderOut;
};

export type SubmitRepairNoTrackingResponse = SubmitRepairNoTrackingResponses[keyof SubmitRepairNoTrackingResponses];

export type SubmitRepairTrackingData = {
    body: RepairTrackingRequest;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/orders/{order_id}/repair-tracking';
};

export type SubmitRepairTrackingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitRepairTrackingError = SubmitRepairTrackingErrors[keyof SubmitRepairTrackingErrors];

export type SubmitRepairTrackingResponses = {
    /**
     * Successful Response
     */
    200: OrderOut;
};

export type SubmitRepairTrackingResponse = SubmitRepairTrackingResponses[keyof SubmitRepairTrackingResponses];

export type ConfirmPaymentData = {
    body: PaymentConfirmRequest;
    path?: never;
    query?: never;
    url: '/payments/confirm';
};

export type ConfirmPaymentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmPaymentError = ConfirmPaymentErrors[keyof ConfirmPaymentErrors];

export type ConfirmPaymentResponses = {
    /**
     * Successful Response
     */
    200: PaymentConfirmResponse;
};

export type ConfirmPaymentResponse = ConfirmPaymentResponses[keyof ConfirmPaymentResponses];

export type ListProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         */
        category?: '3fold' | 'sfolderato' | 'knit' | 'bowtie' | null;
        /**
         * Color
         */
        color?: 'black' | 'navy' | 'gray' | 'wine' | 'blue' | 'brown' | 'beige' | 'silver' | null;
        /**
         * Pattern
         */
        pattern?: 'solid' | 'stripe' | 'dot' | 'check' | 'paisley' | null;
        /**
         * Material
         */
        material?: 'silk' | 'cotton' | 'polyester' | 'wool' | null;
    };
    url: '/products';
};

export type ListProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProductsError = ListProductsErrors[keyof ListProductsErrors];

export type ListProductsResponses = {
    /**
     * Response List Products
     *
     * Successful Response
     */
    200: Array<ProductOut>;
};

export type ListProductsResponse = ListProductsResponses[keyof ListProductsResponses];

export type GetProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/products/{product_id}';
};

export type GetProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
    /**
     * Successful Response
     */
    200: ProductOut;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type UnlikeProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/products/{product_id}/like';
};

export type UnlikeProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlikeProductError = UnlikeProductErrors[keyof UnlikeProductErrors];

export type UnlikeProductResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UnlikeProductResponse = UnlikeProductResponses[keyof UnlikeProductResponses];

export type LikeProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/products/{product_id}/like';
};

export type LikeProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LikeProductError = LikeProductErrors[keyof LikeProductErrors];

export type LikeProductResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LikeProductResponse = LikeProductResponses[keyof LikeProductResponses];

export type ListMyQuotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quotes';
};

export type ListMyQuotesResponses = {
    /**
     * Response List My Quotes
     *
     * Successful Response
     */
    200: Array<QuoteOut>;
};

export type ListMyQuotesResponse = ListMyQuotesResponses[keyof ListMyQuotesResponses];

export type CreateQuoteData = {
    body: QuoteCreateRequest;
    path?: never;
    query?: never;
    url: '/quotes';
};

export type CreateQuoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateQuoteError = CreateQuoteErrors[keyof CreateQuoteErrors];

export type CreateQuoteResponses = {
    /**
     * Successful Response
     */
    201: QuoteOut;
};

export type CreateQuoteResponse = CreateQuoteResponses[keyof CreateQuoteResponses];

export type GetQuoteData = {
    body?: never;
    path: {
        /**
         * Quote Id
         */
        quote_id: string;
    };
    query?: never;
    url: '/quotes/{quote_id}';
};

export type GetQuoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuoteError = GetQuoteErrors[keyof GetQuoteErrors];

export type GetQuoteResponses = {
    /**
     * Successful Response
     */
    200: QuoteOut;
};

export type GetQuoteResponse = GetQuoteResponses[keyof GetQuoteResponses];

export type GetTokenBalanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tokens/balance';
};

export type GetTokenBalanceResponses = {
    /**
     * Successful Response
     */
    200: TokenBalance;
};

export type GetTokenBalanceResponse = GetTokenBalanceResponses[keyof GetTokenBalanceResponses];

export type CreateTokenOrderData = {
    body: TokenOrderCreateRequest;
    path?: never;
    query?: never;
    url: '/tokens/orders';
};

export type CreateTokenOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTokenOrderError = CreateTokenOrderErrors[keyof CreateTokenOrderErrors];

export type CreateTokenOrderResponses = {
    /**
     * Successful Response
     */
    201: TokenOrderCreateResponse;
};

export type CreateTokenOrderResponse = CreateTokenOrderResponses[keyof CreateTokenOrderResponses];

export type GetTokenPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tokens/plans';
};

export type GetTokenPlansResponses = {
    /**
     * Response Get Token Plans
     *
     * Successful Response
     */
    200: Array<TokenPlan>;
};

export type GetTokenPlansResponse = GetTokenPlansResponses[keyof GetTokenPlansResponses];

export type RequestTokenRefundData = {
    body: TokenRefundRequestIn;
    path?: never;
    query?: never;
    url: '/tokens/refund-requests';
};

export type RequestTokenRefundErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestTokenRefundError = RequestTokenRefundErrors[keyof RequestTokenRefundErrors];

export type RequestTokenRefundResponses = {
    /**
     * Successful Response
     */
    201: TokenRefundRequestOut;
};

export type RequestTokenRefundResponse = RequestTokenRefundResponses[keyof RequestTokenRefundResponses];

export type CancelTokenRefundData = {
    body?: never;
    path: {
        /**
         * Claim Id
         */
        claim_id: string;
    };
    query?: never;
    url: '/tokens/refund-requests/{claim_id}/cancel';
};

export type CancelTokenRefundErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTokenRefundError = CancelTokenRefundErrors[keyof CancelTokenRefundErrors];

export type CancelTokenRefundResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CancelTokenRefundResponse = CancelTokenRefundResponses[keyof CancelTokenRefundResponses];

export type ListRefundableTokenOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tokens/refundable-orders';
};

export type ListRefundableTokenOrdersResponses = {
    /**
     * Response List Refundable Token Orders
     *
     * Successful Response
     */
    200: Array<RefundableTokenOrder>;
};

export type ListRefundableTokenOrdersResponse = ListRefundableTokenOrdersResponses[keyof ListRefundableTokenOrdersResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteAccountResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type UpdateProfileData = {
    body: ProfileUpdateRequest;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type ListAddressesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/addresses';
};

export type ListAddressesResponses = {
    /**
     * Response List Addresses
     *
     * Successful Response
     */
    200: Array<ShippingAddressOut>;
};

export type ListAddressesResponse = ListAddressesResponses[keyof ListAddressesResponses];

export type UpsertAddressData = {
    body: ShippingAddressIn;
    path?: never;
    query?: never;
    url: '/users/me/addresses';
};

export type UpsertAddressErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertAddressError = UpsertAddressErrors[keyof UpsertAddressErrors];

export type UpsertAddressResponses = {
    /**
     * Successful Response
     */
    200: ShippingAddressOut;
};

export type UpsertAddressResponse = UpsertAddressResponses[keyof UpsertAddressResponses];

export type DeleteAddressData = {
    body?: never;
    path: {
        /**
         * Address Id
         */
        address_id: string;
    };
    query?: never;
    url: '/users/me/addresses/{address_id}';
};

export type DeleteAddressErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAddressError = DeleteAddressErrors[keyof DeleteAddressErrors];

export type DeleteAddressResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAddressResponse = DeleteAddressResponses[keyof DeleteAddressResponses];

export type SetNotificationPreferencesData = {
    body: NotificationPreferencesRequest;
    path?: never;
    query?: never;
    url: '/users/me/notification-preferences';
};

export type SetNotificationPreferencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetNotificationPreferencesError = SetNotificationPreferencesErrors[keyof SetNotificationPreferencesErrors];

export type SetNotificationPreferencesResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type SetNotificationPreferencesResponse = SetNotificationPreferencesResponses[keyof SetNotificationPreferencesResponses];
