// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AdminClaimStatusRequest
 */
export const zAdminClaimStatusRequest = z.object({
    is_rollback: z.boolean().optional().default(false),
    memo: z.string().nullish(),
    new_status: z.string()
});

/**
 * AdminClaimStatusResponse
 */
export const zAdminClaimStatusResponse = z.object({
    new_status: z.string(),
    previous_status: z.string(),
    success: z.boolean()
});

/**
 * AdminQuoteStatusRequest
 */
export const zAdminQuoteStatusRequest = z.object({
    admin_memo: z.string().nullish(),
    memo: z.string().nullish(),
    new_status: z.enum([
        '요청',
        '견적발송',
        '협의중',
        '확정',
        '종료'
    ]),
    quote_conditions: z.string().nullish(),
    quoted_amount: z.int().nullish()
});

/**
 * AdminQuoteStatusResponse
 */
export const zAdminQuoteStatusResponse = z.object({
    new_status: z.string(),
    previous_status: z.string(),
    success: z.boolean()
});

/**
 * AdminStatusUpdateRequest
 */
export const zAdminStatusUpdateRequest = z.object({
    is_rollback: z.boolean().optional().default(false),
    memo: z.string().nullish(),
    new_status: z.string()
});

/**
 * AdminStatusUpdateResponse
 */
export const zAdminStatusUpdateResponse = z.object({
    new_status: z.string(),
    previous_status: z.string(),
    success: z.boolean()
});

/**
 * AdminTokenManageRequest
 */
export const zAdminTokenManageRequest = z.object({
    amount: z.int(),
    description: z.string(),
    user_id: z.uuid()
});

/**
 * AdminTokenManageResponse
 */
export const zAdminTokenManageResponse = z.object({
    new_balance: z.int(),
    success: z.boolean()
});

/**
 * AdminTrackingUpdateRequest
 */
export const zAdminTrackingUpdateRequest = z.object({
    company_courier_company: z.string().nullish(),
    company_tracking_number: z.string().nullish(),
    courier_company: z.string().nullish(),
    tracking_number: z.string().nullish()
});

/**
 * AdminUserOut
 */
export const zAdminUserOut = z.object({
    created_at: z.iso.datetime(),
    email: z.string().nullable(),
    id: z.uuid(),
    is_active: z.boolean(),
    name: z.string(),
    phone: z.string().nullable(),
    phone_verified: z.boolean(),
    role: z.string()
});

/**
 * AffectedResponse
 */
export const zAffectedResponse = z.object({
    affected_count: z.int(),
    success: z.boolean().optional().default(true)
});

/**
 * BatchResult
 */
export const zBatchResult = z.object({
    processed: z.int()
});

/**
 * CartItemIn
 */
export const zCartItemIn = z.object({
    applied_user_coupon_id: z.uuid().nullish(),
    item_id: z.string(),
    item_type: z.enum(['product', 'reform']),
    product_id: z.int().nullish(),
    quantity: z.int(),
    reform_data: z.record(z.string(), z.unknown()).nullish(),
    selected_option_id: z.string().nullish()
});

/**
 * CartRemoveRequest
 */
export const zCartRemoveRequest = z.object({
    item_ids: z.array(z.string())
});

/**
 * CartReplaceRequest
 */
export const zCartReplaceRequest = z.object({
    items: z.array(zCartItemIn)
});

/**
 * ClaimCreateRequest
 */
export const zClaimCreateRequest = z.object({
    description: z.string().nullish(),
    item_id: z.string(),
    order_id: z.uuid(),
    quantity: z.int().nullish(),
    reason: z.enum([
        'change_mind',
        'defect',
        'delay',
        'wrong_item',
        'size_mismatch',
        'color_mismatch',
        'other'
    ]),
    type: z.enum([
        'cancel',
        'return',
        'exchange'
    ])
});

/**
 * ClaimOut
 */
export const zClaimOut = z.object({
    claim_number: z.string(),
    created_at: z.iso.datetime(),
    description: z.string().nullable(),
    id: z.uuid(),
    order_id: z.uuid(),
    order_item_id: z.uuid(),
    quantity: z.int(),
    reason: z.string(),
    refund_data: z.record(z.string(), z.unknown()).nullable(),
    resend_courier_company: z.string().nullable(),
    resend_tracking_number: z.string().nullable(),
    return_courier_company: z.string().nullable(),
    return_tracking_number: z.string().nullable(),
    status: z.string(),
    type: z.string(),
    updated_at: z.iso.datetime(),
    user_id: z.uuid()
});

/**
 * ConfirmedOrder
 */
export const zConfirmedOrder = z.object({
    coupon_issued: z.boolean().optional().default(false),
    order_id: z.uuid(),
    order_number: z.string(),
    order_type: z.string(),
    status: z.string(),
    token_amount: z.int().nullish()
});

/**
 * CouponCreateRequest
 */
export const zCouponCreateRequest = z.object({
    description: z.string().nullish(),
    discount_type: z.enum(['percentage', 'fixed']),
    discount_value: z.int(),
    display_name: z.string().nullish(),
    expiry_date: z.iso.date(),
    max_discount_amount: z.int().nullish(),
    name: z.string()
});

/**
 * CouponIssueRequest
 */
export const zCouponIssueRequest = z.object({
    user_ids: z.array(z.uuid())
});

/**
 * CouponOut
 */
export const zCouponOut = z.object({
    additional_info: z.string().nullable(),
    description: z.string().nullable(),
    discount_type: z.string(),
    discount_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    display_name: z.string().nullable(),
    expiry_date: z.iso.date(),
    id: z.uuid(),
    is_active: z.boolean(),
    max_discount_amount: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/).nullable(),
    name: z.string()
});

/**
 * CreatedOrder
 */
export const zCreatedOrder = z.object({
    order_id: z.uuid(),
    order_number: z.string(),
    order_type: z.string()
});

/**
 * CustomAmountRequest
 */
export const zCustomAmountRequest = z.object({
    options: z.record(z.string(), z.unknown()),
    quantity: z.int()
});

/**
 * CustomAmountResponse
 */
export const zCustomAmountResponse = z.object({
    fabric_cost: z.int(),
    sewing_cost: z.int(),
    total_cost: z.int()
});

/**
 * DesignGenerateRequest
 */
export const zDesignGenerateRequest = z.object({
    candidate_count: z.int().optional().default(1),
    colorway: z.string().nullish(),
    intent: z.record(z.string(), z.unknown()).nullish(),
    prompt: z.string().nullish(),
    seed: z.int().nullish(),
    session_id: z.uuid().nullish()
});

/**
 * DesignSessionOut
 */
export const zDesignSessionOut = z.object({
    colorway: z.string().nullable(),
    created_at: z.iso.datetime(),
    current_intent: z.record(z.string(), z.unknown()).nullable(),
    finalize_used: z.int(),
    id: z.uuid(),
    recraft_used: z.int(),
    registry_version: z.string().nullable(),
    seed: z.int().nullable(),
    status: z.string(),
    updated_at: z.iso.datetime()
});

/**
 * DesignSessionUpdateRequest
 */
export const zDesignSessionUpdateRequest = z.object({
    colorway: z.string().nullish(),
    current_intent: z.record(z.string(), z.unknown()).nullish(),
    seed: z.int().nullish()
});

/**
 * DesignTurnCreateRequest
 */
export const zDesignTurnCreateRequest = z.object({
    payload: z.record(z.string(), z.unknown()),
    role: z.string()
});

/**
 * DesignTurnOut
 */
export const zDesignTurnOut = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid(),
    payload: z.record(z.string(), z.unknown()),
    role: z.string(),
    seq: z.int()
});

/**
 * FinalizeRequest
 */
export const zFinalizeRequest = z.object({
    colorway_id: z.string().nullish(),
    dpi: z.int().nullish(),
    intent: z.record(z.string(), z.unknown()).nullish(),
    material_map: z.record(z.string(), z.string()).nullish(),
    production_method: z.string().nullish(),
    relief_strength: z.number().gte(0).nullish(),
    texture_strength: z.number().gte(0).nullish(),
    weave: z.string().nullish()
});

/**
 * GenerationJobOut
 */
export const zGenerationJobOut = z.object({
    attempts: z.int(),
    created_at: z.iso.datetime(),
    error_message: z.string().nullable(),
    id: z.uuid(),
    kind: z.string(),
    params: z.record(z.string(), z.unknown()),
    request_id: z.string().nullable(),
    result: z.record(z.string(), z.unknown()).nullable(),
    session_id: z.uuid().nullable(),
    status: z.string(),
    updated_at: z.iso.datetime()
});

/**
 * ImageOut
 */
export const zImageOut = z.object({
    created_at: z.iso.datetime(),
    entity_id: z.string(),
    entity_type: z.string(),
    expires_at: z.iso.datetime().nullable(),
    id: z.uuid(),
    object_key: z.string()
});

/**
 * InquiryAnswerRequest
 */
export const zInquiryAnswerRequest = z.object({
    answer: z.string().min(1)
});

/**
 * InquiryCreateRequest
 */
export const zInquiryCreateRequest = z.object({
    category: z.enum([
        '일반',
        '상품',
        '수선',
        '주문제작'
    ]).optional().default('일반'),
    content: z.string().min(1).max(5000),
    product_id: z.int().nullish(),
    title: z.string().min(1).max(200)
});

/**
 * InquiryOut
 */
export const zInquiryOut = z.object({
    answer: z.string().nullable(),
    answer_date: z.iso.datetime().nullable(),
    category: z.string(),
    content: z.string(),
    created_at: z.iso.datetime(),
    id: z.uuid(),
    product_id: z.int().nullable(),
    status: z.string(),
    title: z.string()
});

/**
 * LoginRequest
 */
export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string()
});

/**
 * MeResponse
 */
export const zMeResponse = z.object({
    birth: z.iso.date().nullable(),
    created_at: z.iso.datetime(),
    email: z.string().nullable(),
    id: z.uuid(),
    marketing_kakao_sms_consent: z.boolean(),
    name: z.string(),
    notification_consent: z.boolean(),
    notification_enabled: z.boolean(),
    phone: z.string().nullable(),
    phone_verified: z.boolean(),
    role: z.string()
});

/**
 * MessageResponse
 */
export const zMessageResponse = z.object({
    message: z.string()
});

/**
 * MotifCandidateOut
 */
export const zMotifCandidateOut = z.object({
    description: z.string().nullish(),
    motif_id: z.string(),
    scope: z.string().nullish(),
    similarity: z.number().nullable(),
    source: z.string().nullish(),
    style: z.string().nullish(),
    subject: z.string().nullish(),
    view: z.string().nullish()
});

/**
 * MotifCandidatesOut
 */
export const zMotifCandidatesOut = z.object({
    candidates: z.array(zMotifCandidateOut),
    registry_version: z.string(),
    request_id: z.string()
});

/**
 * MotifGenerateOut
 */
export const zMotifGenerateOut = z.object({
    motif_id: z.string(),
    request_id: z.string(),
    reused: z.boolean(),
    similarity: z.number().nullable()
});

/**
 * MotifSpecIn
 */
export const zMotifSpecIn = z.object({
    description: z.string().nullish(),
    expression: z.string().nullish(),
    scope: z.string(),
    style: z.string().nullish(),
    subject: z.string(),
    view: z.string().nullish()
});

/**
 * MotifCandidatesRequest
 */
export const zMotifCandidatesRequest = z.object({
    spec: zMotifSpecIn,
    top_k: z.int().gte(1).lte(10).optional().default(5)
});

/**
 * MotifGenerateRequest
 */
export const zMotifGenerateRequest = z.object({
    seed: z.int().nullish(),
    spec: zMotifSpecIn
});

/**
 * NotificationPreferencesRequest
 */
export const zNotificationPreferencesRequest = z.object({
    notification_consent: z.boolean().nullish(),
    notification_enabled: z.boolean().nullish()
});

/**
 * OrderCreateResponse
 */
export const zOrderCreateResponse = z.object({
    orders: z.array(zCreatedOrder),
    payment_group_id: z.uuid(),
    total_amount: z.int()
});

/**
 * OrderItemIn
 */
export const zOrderItemIn = z.object({
    applied_user_coupon_id: z.uuid().nullish(),
    item_id: z.string(),
    item_type: z.enum(['product', 'reform']),
    product_id: z.int().nullish(),
    quantity: z.int(),
    reform_data: z.record(z.string(), z.unknown()).nullish(),
    selected_option_id: z.string().nullish()
});

/**
 * OrderItemOut
 */
export const zOrderItemOut = z.object({
    applied_user_coupon_id: z.uuid().nullable(),
    discount_amount: z.int(),
    id: z.uuid(),
    item_data: z.record(z.string(), z.unknown()).nullable(),
    item_id: z.string(),
    item_type: z.string(),
    line_discount_amount: z.int(),
    product_id: z.int().nullable(),
    quantity: z.int(),
    selected_option_id: z.string().nullable(),
    unit_price: z.int()
});

/**
 * AdminOrderOut
 */
export const zAdminOrderOut = z.object({
    admin_actions: z.array(z.string()).optional().default([]),
    company_courier_company: z.string().nullable(),
    company_shipped_at: z.iso.datetime().nullable(),
    company_tracking_number: z.string().nullable(),
    confirmed_at: z.iso.datetime().nullable(),
    courier_company: z.string().nullable(),
    created_at: z.iso.datetime(),
    customer_actions: z.array(z.string()).optional().default([]),
    delivered_at: z.iso.datetime().nullable(),
    id: z.uuid(),
    items: z.array(zOrderItemOut).optional().default([]),
    order_number: z.string(),
    order_type: z.string(),
    original_price: z.int(),
    payment_group_id: z.uuid().nullable(),
    shipped_at: z.iso.datetime().nullable(),
    shipping_address_id: z.uuid().nullable(),
    shipping_cost: z.int(),
    status: z.string(),
    total_discount: z.int(),
    total_price: z.int(),
    tracking_number: z.string().nullable(),
    updated_at: z.iso.datetime()
});

/**
 * OrderOut
 */
export const zOrderOut = z.object({
    company_courier_company: z.string().nullable(),
    company_shipped_at: z.iso.datetime().nullable(),
    company_tracking_number: z.string().nullable(),
    confirmed_at: z.iso.datetime().nullable(),
    courier_company: z.string().nullable(),
    created_at: z.iso.datetime(),
    customer_actions: z.array(z.string()).optional().default([]),
    delivered_at: z.iso.datetime().nullable(),
    id: z.uuid(),
    items: z.array(zOrderItemOut).optional().default([]),
    order_number: z.string(),
    order_type: z.string(),
    original_price: z.int(),
    payment_group_id: z.uuid().nullable(),
    shipped_at: z.iso.datetime().nullable(),
    shipping_address_id: z.uuid().nullable(),
    shipping_cost: z.int(),
    status: z.string(),
    total_discount: z.int(),
    total_price: z.int(),
    tracking_number: z.string().nullable(),
    updated_at: z.iso.datetime()
});

/**
 * PaymentConfirmRequest
 */
export const zPaymentConfirmRequest = z.object({
    amount: z.int(),
    payment_group_id: z.uuid(),
    payment_key: z.string()
});

/**
 * PaymentConfirmResponse
 */
export const zPaymentConfirmResponse = z.object({
    orders: z.array(zConfirmedOrder),
    success: z.boolean().optional().default(true),
    token_amount: z.int().nullish()
});

/**
 * PhoneSendRequest
 */
export const zPhoneSendRequest = z.object({
    phone: z.string()
});

/**
 * PhoneVerifyRequest
 */
export const zPhoneVerifyRequest = z.object({
    code: z.string(),
    phone: z.string()
});

/**
 * ProductCreate
 */
export const zProductCreate = z.object({
    category: z.enum([
        '3fold',
        'sfolderato',
        'knit',
        'bowtie'
    ]),
    code: z.string().nullish(),
    color: z.enum([
        'black',
        'navy',
        'gray',
        'wine',
        'blue',
        'brown',
        'beige',
        'silver'
    ]),
    detail_images: z.array(z.string()).nullish(),
    image: z.string(),
    info: z.string(),
    material: z.enum([
        'silk',
        'cotton',
        'polyester',
        'wool'
    ]),
    name: z.string(),
    option_label: z.string().nullish(),
    pattern: z.enum([
        'solid',
        'stripe',
        'dot',
        'check',
        'paisley'
    ]),
    price: z.int(),
    stock: z.int().nullish()
});

/**
 * ProductOptionIn
 */
export const zProductOptionIn = z.object({
    additional_price: z.int().optional().default(0),
    name: z.string(),
    stock: z.int().nullish()
});

/**
 * ProductOptionOut
 */
export const zProductOptionOut = z.object({
    additional_price: z.int(),
    id: z.uuid(),
    name: z.string(),
    stock: z.int().nullable()
});

/**
 * ProductOut
 */
export const zProductOut = z.object({
    category: z.string(),
    code: z.string().nullable(),
    color: z.string(),
    created_at: z.iso.datetime(),
    detail_images: z.array(z.string()).nullable(),
    id: z.int(),
    image: z.string(),
    info: z.string(),
    is_liked: z.boolean().optional().default(false),
    likes: z.int().optional().default(0),
    material: z.string(),
    name: z.string(),
    option_label: z.string().nullable(),
    options: z.array(zProductOptionOut).optional().default([]),
    pattern: z.string(),
    price: z.int(),
    stock: z.int().nullable(),
    updated_at: z.iso.datetime()
});

/**
 * ProductUpdate
 */
export const zProductUpdate = z.object({
    category: z.enum([
        '3fold',
        'sfolderato',
        'knit',
        'bowtie'
    ]).nullish(),
    color: z.enum([
        'black',
        'navy',
        'gray',
        'wine',
        'blue',
        'brown',
        'beige',
        'silver'
    ]).nullish(),
    detail_images: z.array(z.string()).nullish(),
    image: z.string().nullish(),
    info: z.string().nullish(),
    material: z.enum([
        'silk',
        'cotton',
        'polyester',
        'wool'
    ]).nullish(),
    name: z.string().nullish(),
    option_label: z.string().nullish(),
    pattern: z.enum([
        'solid',
        'stripe',
        'dot',
        'check',
        'paisley'
    ]).nullish(),
    price: z.int().nullish(),
    stock: z.int().nullish()
});

/**
 * ProfileUpdateRequest
 *
 * 본인 수정 허용 필드만 — phone_verified/notification_*role은 전용 경로.
 */
export const zProfileUpdateRequest = z.object({
    birth: z.iso.date().nullish(),
    marketing_kakao_sms_consent: z.boolean().nullish(),
    name: z.string().nullish(),
    phone: z.string().nullish()
});

/**
 * QuoteOut
 */
export const zQuoteOut = z.object({
    additional_notes: z.string(),
    admin_memo: z.string().nullable(),
    business_name: z.string(),
    contact_method: z.string(),
    contact_name: z.string(),
    contact_value: z.string(),
    created_at: z.iso.datetime(),
    id: z.uuid(),
    options: z.record(z.string(), z.unknown()),
    quantity: z.int(),
    quote_conditions: z.string().nullable(),
    quote_number: z.string(),
    quoted_amount: z.int().nullable(),
    reference_images: z.array(z.unknown()),
    shipping_address_id: z.uuid(),
    status: z.string(),
    updated_at: z.iso.datetime(),
    user_id: z.uuid()
});

/**
 * ReferenceImageIn
 */
export const zReferenceImageIn = z.object({
    object_key: z.string()
});

/**
 * CustomOrderCreateRequest
 */
export const zCustomOrderCreateRequest = z.object({
    additional_notes: z.string().optional().default(''),
    options: z.record(z.string(), z.unknown()),
    quantity: z.int(),
    reference_images: z.array(zReferenceImageIn).optional().default([]),
    shipping_address_id: z.uuid(),
    user_coupon_id: z.uuid().nullish()
});

/**
 * QuoteCreateRequest
 */
export const zQuoteCreateRequest = z.object({
    additional_notes: z.string().optional().default(''),
    business_name: z.string().optional().default(''),
    contact_method: z.enum(['email', 'phone']),
    contact_name: z.string(),
    contact_value: z.string(),
    options: z.record(z.string(), z.unknown()),
    quantity: z.int(),
    reference_images: z.array(zReferenceImageIn).optional().default([]),
    shipping_address_id: z.uuid()
});

/**
 * RefundableTokenOrder
 */
export const zRefundableTokenOrder = z.object({
    is_refundable: z.boolean(),
    order_id: z.uuid(),
    order_number: z.string(),
    paid_tokens_granted: z.int(),
    reason: z.string().nullable(),
    token_expires_at: z.iso.datetime().nullable(),
    total_price: z.int()
});

/**
 * RepairPhotoIn
 */
export const zRepairPhotoIn = z.object({
    object_key: z.string()
});

/**
 * RepairNoTrackingRequest
 */
export const zRepairNoTrackingRequest = z.object({
    memo: z.string().nullish(),
    photos: z.array(zRepairPhotoIn).optional().default([]),
    reason: z.enum([
        'quick',
        'overseas',
        'lost'
    ])
});

/**
 * RepairPickupIn
 */
export const zRepairPickupIn = z.object({
    address: z.string(),
    detail_address: z.string().nullish(),
    postal_code: z.string().nullish(),
    recipient_name: z.string(),
    recipient_phone: z.string()
});

/**
 * RepairShippingIn
 */
export const zRepairShippingIn = z.object({
    method: z.enum(['direct', 'pickup']),
    pickup: zRepairPickupIn.nullish()
});

/**
 * OrderCreateRequest
 */
export const zOrderCreateRequest = z.object({
    items: z.array(zOrderItemIn),
    repair_shipping: zRepairShippingIn.nullish(),
    shipping_address_id: z.uuid()
});

/**
 * RepairTrackingRequest
 */
export const zRepairTrackingRequest = z.object({
    courier_company: z.string(),
    photos: z.array(zRepairPhotoIn).optional().default([]),
    tracking_number: z.string()
});

/**
 * RevokeByIdsRequest
 */
export const zRevokeByIdsRequest = z.object({
    user_coupon_ids: z.array(z.uuid())
});

/**
 * SampleOrderCreateRequest
 */
export const zSampleOrderCreateRequest = z.object({
    additional_notes: z.string().optional().default(''),
    options: z.record(z.string(), z.unknown()),
    reference_images: z.array(zReferenceImageIn).optional().default([]),
    sample_type: z.enum([
        'fabric',
        'sewing',
        'fabric_and_sewing'
    ]),
    shipping_address_id: z.uuid(),
    user_coupon_id: z.uuid().nullish()
});

/**
 * ShippingAddressIn
 */
export const zShippingAddressIn = z.object({
    address: z.string(),
    address_detail: z.string().nullish(),
    delivery_memo: z.string().nullish(),
    delivery_request: z.string().nullish(),
    id: z.uuid().nullish(),
    is_default: z.boolean().optional().default(false),
    postal_code: z.string(),
    recipient_name: z.string(),
    recipient_phone: z.string()
});

/**
 * ShippingAddressOut
 */
export const zShippingAddressOut = z.object({
    address: z.string(),
    address_detail: z.string().nullable(),
    created_at: z.iso.datetime(),
    delivery_memo: z.string().nullable(),
    delivery_request: z.string().nullable(),
    id: z.uuid(),
    is_default: z.boolean(),
    postal_code: z.string(),
    recipient_name: z.string(),
    recipient_phone: z.string()
});

/**
 * SingleOrderCreateResponse
 */
export const zSingleOrderCreateResponse = z.object({
    order_id: z.uuid(),
    order_number: z.string(),
    payment_group_id: z.uuid(),
    total_amount: z.int()
});

/**
 * StatsResponse
 */
export const zStatsResponse = z.object({
    order_count: z.int(),
    revenue: z.int()
});

/**
 * TokenBalance
 */
export const zTokenBalance = z.object({
    bonus: z.int(),
    paid: z.int(),
    total: z.int()
});

/**
 * TokenOrderCreateRequest
 */
export const zTokenOrderCreateRequest = z.object({
    plan_key: z.enum([
        'starter',
        'popular',
        'pro'
    ])
});

/**
 * TokenOrderCreateResponse
 */
export const zTokenOrderCreateResponse = z.object({
    order_id: z.uuid(),
    order_number: z.string(),
    payment_group_id: z.uuid(),
    price: z.int(),
    token_amount: z.int()
});

/**
 * TokenPlan
 */
export const zTokenPlan = z.object({
    plan_key: z.string(),
    price: z.int(),
    token_amount: z.int()
});

/**
 * TokenRefundRequestIn
 */
export const zTokenRefundRequestIn = z.object({
    order_id: z.uuid()
});

/**
 * TokenRefundRequestOut
 */
export const zTokenRefundRequestOut = z.object({
    bonus_token_amount: z.int(),
    claim_id: z.uuid(),
    claim_number: z.string(),
    paid_token_amount: z.int(),
    refund_amount: z.int()
});

/**
 * TokenResponse
 */
export const zTokenResponse = z.object({
    access_token: z.string(),
    token_type: z.string().optional().default('bearer')
});

/**
 * UploadRegisterRequest
 */
export const zUploadRegisterRequest = z.object({
    object_key: z.string()
});

/**
 * UploadUrlRequest
 */
export const zUploadUrlRequest = z.object({
    content_type: z.string(),
    filename: z.string(),
    kind: z.enum([
        'reform_upload',
        'repair_shipping_upload',
        'custom_order',
        'sample_order',
        'quote_request'
    ])
});

/**
 * UploadUrlResponse
 */
export const zUploadUrlResponse = z.object({
    object_key: z.string(),
    upload_url: z.string()
});

/**
 * UserCouponOut
 */
export const zUserCouponOut = z.object({
    coupon: zCouponOut.nullish(),
    coupon_id: z.uuid(),
    expires_at: z.iso.datetime().nullable(),
    id: z.uuid(),
    issued_at: z.iso.datetime(),
    status: z.string(),
    used_at: z.iso.datetime().nullable()
});

/**
 * CartItemOut
 */
export const zCartItemOut = z.object({
    applied_coupon: zUserCouponOut.nullable(),
    item_id: z.string(),
    item_type: z.string(),
    product: zProductOut.nullable(),
    quantity: z.int(),
    reform_data: z.record(z.string(), z.unknown()).nullable(),
    selected_option: zProductOptionOut.nullable()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * WebhookResult
 */
export const zWebhookResult = z.object({
    action: z.string().nullish(),
    handled: z.boolean(),
    orders: z.int().nullish(),
    reason: z.string().nullish()
});

/**
 * WorkerCandidateOut
 */
export const zWorkerCandidateOut = z.object({
    colorway_id: z.string(),
    design_index: z.int(),
    id: z.string(),
    layout_id: z.string(),
    png_object_key: z.string().nullable(),
    seed: z.int(),
    source_fidelity: z.string(),
    svg: z.string()
});

/**
 * DesignGenerateOut
 */
export const zDesignGenerateOut = z.object({
    candidates: z.array(zWorkerCandidateOut),
    engine_version: z.string(),
    registry_version: z.string(),
    request_id: z.string(),
    warnings: z.array(z.string()).optional().default([])
});

/**
 * Response Admin List Claims
 *
 * Successful Response
 */
export const zAdminListClaimsResponse = z.array(zClaimOut);

export const zAdminUpdateClaimStatusBody = zAdminClaimStatusRequest;

export const zAdminUpdateClaimStatusPath = z.object({
    claim_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAdminUpdateClaimStatusResponse = zAdminClaimStatusResponse;

/**
 * Response List Coupons
 *
 * Successful Response
 */
export const zListCouponsResponse = z.array(zCouponOut);

export const zCreateCouponBody = zCouponCreateRequest;

/**
 * Successful Response
 */
export const zCreateCouponResponse = zCouponOut;

export const zRevokeCouponsByIdsBody = zRevokeByIdsRequest;

/**
 * Successful Response
 */
export const zRevokeCouponsByIdsResponse = zAffectedResponse;

export const zBulkIssueCouponsBody = zCouponIssueRequest;

export const zBulkIssueCouponsPath = z.object({
    coupon_id: z.uuid()
});

/**
 * Successful Response
 */
export const zBulkIssueCouponsResponse = zAffectedResponse;

export const zRevokeCouponsByUsersBody = zCouponIssueRequest;

export const zRevokeCouponsByUsersPath = z.object({
    coupon_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRevokeCouponsByUsersResponse = zAffectedResponse;

/**
 * Response Admin List Inquiries
 *
 * Successful Response
 */
export const zAdminListInquiriesResponse = z.array(zInquiryOut);

export const zAnswerInquiryBody = zInquiryAnswerRequest;

export const zAnswerInquiryPath = z.object({
    inquiry_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAnswerInquiryResponse = zInquiryOut;

export const zListAllOrdersQuery = z.object({
    order_type: z.enum([
        'all',
        'sale',
        'custom',
        'repair',
        'token',
        'sample'
    ]).optional().default('all'),
    status: z.string().nullish()
});

/**
 * Response List All Orders
 *
 * Successful Response
 */
export const zListAllOrdersResponse = z.array(zAdminOrderOut);

export const zAdminUpdateOrderStatusBody = zAdminStatusUpdateRequest;

export const zAdminUpdateOrderStatusPath = z.object({
    order_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAdminUpdateOrderStatusResponse = zAdminStatusUpdateResponse;

export const zAdminUpdateOrderTrackingBody = zAdminTrackingUpdateRequest;

export const zAdminUpdateOrderTrackingPath = z.object({
    order_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAdminUpdateOrderTrackingResponse = zOrderOut;

export const zCreateProductBody = zProductCreate;

/**
 * Successful Response
 */
export const zCreateProductResponse = zProductOut;

export const zUpdateProductBody = zProductUpdate;

export const zUpdateProductPath = z.object({
    product_id: z.int()
});

/**
 * Successful Response
 */
export const zUpdateProductResponse = zProductOut;

/**
 * Body
 */
export const zReplaceProductOptionsBody = z.array(zProductOptionIn);

export const zReplaceProductOptionsPath = z.object({
    product_id: z.int()
});

/**
 * Response Replace Product Options
 *
 * Successful Response
 */
export const zReplaceProductOptionsResponse = z.array(zProductOptionOut);

/**
 * Response Admin List Quotes
 *
 * Successful Response
 */
export const zAdminListQuotesResponse = z.array(zQuoteOut);

export const zAdminUpdateQuoteStatusBody = zAdminQuoteStatusRequest;

export const zAdminUpdateQuoteStatusPath = z.object({
    quote_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAdminUpdateQuoteStatusResponse = zAdminQuoteStatusResponse;

export const zPeriodStatsQuery = z.object({
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    order_type: z.enum([
        'all',
        'sale',
        'custom',
        'repair',
        'token',
        'sample'
    ]).optional().default('all')
});

/**
 * Successful Response
 */
export const zPeriodStatsResponse = zStatsResponse;

export const zTodayStatsQuery = z.object({
    stat_date: z.iso.date(),
    order_type: z.enum([
        'all',
        'sale',
        'custom',
        'repair',
        'token',
        'sample'
    ]).optional().default('all')
});

/**
 * Successful Response
 */
export const zTodayStatsResponse = zStatsResponse;

export const zAdminApproveTokenRefundPath = z.object({
    claim_id: z.uuid()
});

/**
 * Response Admin Approve Token Refund
 *
 * Successful Response
 */
export const zAdminApproveTokenRefundResponse = z.record(z.string(), z.unknown());

export const zAdminManageTokensBody = zAdminTokenManageRequest;

/**
 * Successful Response
 */
export const zAdminManageTokensResponse = zAdminTokenManageResponse;

/**
 * Response List Users
 *
 * Successful Response
 */
export const zListUsersResponse = z.array(zAdminUserOut);

export const zLoginBody = zLoginRequest;

/**
 * Successful Response
 */
export const zLoginResponse = zTokenResponse;

/**
 * Successful Response
 */
export const zLogoutResponse = z.void();

/**
 * Successful Response
 */
export const zGetMeResponse = zMeResponse;

export const zSendPhoneVerificationBody = zPhoneSendRequest;

/**
 * Successful Response
 */
export const zSendPhoneVerificationResponse = zMessageResponse;

export const zVerifyPhoneBody = zPhoneVerifyRequest;

/**
 * Successful Response
 */
export const zVerifyPhoneResponse = zMessageResponse;

/**
 * Successful Response
 */
export const zRefreshTokensResponse = zTokenResponse;

/**
 * Successful Response
 */
export const zAutoConfirmOrdersResponse = zBatchResult;

/**
 * Successful Response
 */
export const zCancelStaleOrdersResponse = zBatchResult;

/**
 * Successful Response
 */
export const zCleanupImagesResponse = zBatchResult;

/**
 * Response Get Cart
 *
 * Successful Response
 */
export const zGetCartResponse = z.array(zCartItemOut);

export const zReplaceCartBody = zCartReplaceRequest;

/**
 * Response Replace Cart
 *
 * Successful Response
 */
export const zReplaceCartResponse = z.array(zCartItemOut);

export const zRemoveCartItemsBody = zCartRemoveRequest;

/**
 * Response Remove Cart Items
 *
 * Successful Response
 */
export const zRemoveCartItemsResponse = z.array(zCartItemOut);

/**
 * Response List My Claims
 *
 * Successful Response
 */
export const zListMyClaimsResponse = z.array(zClaimOut);

export const zCreateClaimBody = zClaimCreateRequest;

/**
 * Successful Response
 */
export const zCreateClaimResponse = zClaimOut;

export const zCancelClaimPath = z.object({
    claim_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCancelClaimResponse = z.void();

export const zListMyCouponsQuery = z.object({
    active_only: z.boolean().optional().default(false)
});

/**
 * Response List My Coupons
 *
 * Successful Response
 */
export const zListMyCouponsResponse = z.array(zUserCouponOut);

export const zGenerateDesignBody = zDesignGenerateRequest;

/**
 * Successful Response
 */
export const zGenerateDesignResponse = zDesignGenerateOut;

export const zGetGenerationJobPath = z.object({
    job_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetGenerationJobResponse = zGenerationJobOut;

/**
 * Response List Design Sessions
 *
 * Successful Response
 */
export const zListDesignSessionsResponse = z.array(zDesignSessionOut);

/**
 * Successful Response
 */
export const zCreateDesignSessionResponse = zDesignSessionOut;

export const zGetDesignSessionPath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetDesignSessionResponse = zDesignSessionOut;

export const zUpdateDesignSessionBody = zDesignSessionUpdateRequest;

export const zUpdateDesignSessionPath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateDesignSessionResponse = zDesignSessionOut;

export const zCreateFinalizeJobBody = zFinalizeRequest;

export const zCreateFinalizeJobPath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateFinalizeJobResponse = zGenerationJobOut;

export const zMotifCandidatesBody = zMotifCandidatesRequest;

export const zMotifCandidatesPath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zMotifCandidatesResponse = zMotifCandidatesOut;

export const zMotifGenerateBody = zMotifGenerateRequest;

export const zMotifGeneratePath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zMotifGenerateResponse = zMotifGenerateOut;

export const zListDesignTurnsPath = z.object({
    session_id: z.uuid()
});

/**
 * Response List Design Turns
 *
 * Successful Response
 */
export const zListDesignTurnsResponse = z.array(zDesignTurnOut);

export const zAppendDesignTurnBody = zDesignTurnCreateRequest;

export const zAppendDesignTurnPath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAppendDesignTurnResponse = zDesignTurnOut;

/**
 * Response Healthz
 *
 * Successful Response
 */
export const zHealthzResponse = z.record(z.string(), z.string());

export const zRegisterReformUploadBody = zUploadRegisterRequest;

/**
 * Successful Response
 */
export const zRegisterReformUploadResponse = zImageOut;

export const zRegisterRepairShippingUploadBody = zUploadRegisterRequest;

/**
 * Successful Response
 */
export const zRegisterRepairShippingUploadResponse = zImageOut;

export const zCreateUploadUrlBody = zUploadUrlRequest;

/**
 * Successful Response
 */
export const zCreateUploadUrlResponse = zUploadUrlResponse;

/**
 * Response List My Inquiries
 *
 * Successful Response
 */
export const zListMyInquiriesResponse = z.array(zInquiryOut);

export const zCreateInquiryBody = zInquiryCreateRequest;

/**
 * Successful Response
 */
export const zCreateInquiryResponse = zInquiryOut;

export const zGetInquiryPath = z.object({
    inquiry_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetInquiryResponse = zInquiryOut;

export const zListMyOrdersQuery = z.object({
    order_type: z.enum([
        'sale',
        'custom',
        'repair',
        'token',
        'sample'
    ]).nullish()
});

/**
 * Response List My Orders
 *
 * Successful Response
 */
export const zListMyOrdersResponse = z.array(zOrderOut);

export const zCreateOrderBody = zOrderCreateRequest;

/**
 * Successful Response
 */
export const zCreateOrderResponse = zOrderCreateResponse;

export const zCreateCustomOrderBody = zCustomOrderCreateRequest;

/**
 * Successful Response
 */
export const zCreateCustomOrderResponse = zSingleOrderCreateResponse;

export const zCalculateCustomOrderBody = zCustomAmountRequest;

/**
 * Successful Response
 */
export const zCalculateCustomOrderResponse = zCustomAmountResponse;

export const zCreateSampleOrderBody = zSampleOrderCreateRequest;

/**
 * Successful Response
 */
export const zCreateSampleOrderResponse = zSingleOrderCreateResponse;

export const zGetOrderPath = z.object({
    order_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetOrderResponse = zOrderOut;

export const zConfirmPurchasePath = z.object({
    order_id: z.uuid()
});

/**
 * Successful Response
 */
export const zConfirmPurchaseResponse = zOrderOut;

export const zSubmitRepairNoTrackingBody = zRepairNoTrackingRequest;

export const zSubmitRepairNoTrackingPath = z.object({
    order_id: z.uuid()
});

/**
 * Successful Response
 */
export const zSubmitRepairNoTrackingResponse = zOrderOut;

export const zSubmitRepairTrackingBody = zRepairTrackingRequest;

export const zSubmitRepairTrackingPath = z.object({
    order_id: z.uuid()
});

/**
 * Successful Response
 */
export const zSubmitRepairTrackingResponse = zOrderOut;

export const zConfirmPaymentBody = zPaymentConfirmRequest;

/**
 * Successful Response
 */
export const zConfirmPaymentResponse = zPaymentConfirmResponse;

/**
 * Payload
 */
export const zTossWebhookBody = z.record(z.string(), z.unknown());

/**
 * Successful Response
 */
export const zTossWebhookResponse = zWebhookResult;

export const zListProductsQuery = z.object({
    category: z.enum([
        '3fold',
        'sfolderato',
        'knit',
        'bowtie'
    ]).nullish(),
    color: z.enum([
        'black',
        'navy',
        'gray',
        'wine',
        'blue',
        'brown',
        'beige',
        'silver'
    ]).nullish(),
    pattern: z.enum([
        'solid',
        'stripe',
        'dot',
        'check',
        'paisley'
    ]).nullish(),
    material: z.enum([
        'silk',
        'cotton',
        'polyester',
        'wool'
    ]).nullish()
});

/**
 * Response List Products
 *
 * Successful Response
 */
export const zListProductsResponse = z.array(zProductOut);

export const zGetProductPath = z.object({
    product_id: z.int()
});

/**
 * Successful Response
 */
export const zGetProductResponse = zProductOut;

export const zUnlikeProductPath = z.object({
    product_id: z.int()
});

/**
 * Successful Response
 */
export const zUnlikeProductResponse = z.void();

export const zLikeProductPath = z.object({
    product_id: z.int()
});

/**
 * Successful Response
 */
export const zLikeProductResponse = z.void();

/**
 * Response List My Quotes
 *
 * Successful Response
 */
export const zListMyQuotesResponse = z.array(zQuoteOut);

export const zCreateQuoteBody = zQuoteCreateRequest;

/**
 * Successful Response
 */
export const zCreateQuoteResponse = zQuoteOut;

export const zGetQuotePath = z.object({
    quote_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetQuoteResponse = zQuoteOut;

/**
 * Successful Response
 */
export const zGetTokenBalanceResponse = zTokenBalance;

export const zCreateTokenOrderBody = zTokenOrderCreateRequest;

/**
 * Successful Response
 */
export const zCreateTokenOrderResponse = zTokenOrderCreateResponse;

/**
 * Response Get Token Plans
 *
 * Successful Response
 */
export const zGetTokenPlansResponse = z.array(zTokenPlan);

export const zRequestTokenRefundBody = zTokenRefundRequestIn;

/**
 * Successful Response
 */
export const zRequestTokenRefundResponse = zTokenRefundRequestOut;

export const zCancelTokenRefundPath = z.object({
    claim_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCancelTokenRefundResponse = z.void();

/**
 * Response List Refundable Token Orders
 *
 * Successful Response
 */
export const zListRefundableTokenOrdersResponse = z.array(zRefundableTokenOrder);

/**
 * Successful Response
 */
export const zDeleteAccountResponse = z.void();

export const zUpdateProfileBody = zProfileUpdateRequest;

/**
 * Successful Response
 */
export const zUpdateProfileResponse = zMeResponse;

/**
 * Response List Addresses
 *
 * Successful Response
 */
export const zListAddressesResponse = z.array(zShippingAddressOut);

export const zUpsertAddressBody = zShippingAddressIn;

/**
 * Successful Response
 */
export const zUpsertAddressResponse = zShippingAddressOut;

export const zDeleteAddressPath = z.object({
    address_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteAddressResponse = z.void();

export const zSetNotificationPreferencesBody = zNotificationPreferencesRequest;

/**
 * Successful Response
 */
export const zSetNotificationPreferencesResponse = zMeResponse;
